"""Small real-board 47DR waveform examples.

All editable frequency values in this module are GHz and all pulse lengths
are ns.  The 47DR RFDC accepts a 400 MS/s complex baseband stream, so the
requested RF carrier is generated by the RFDC NCO while the uploaded IQ
waveform is normally a DC envelope.  This is important for carriers such as
1.79 GHz, which cannot be represented directly in a 400 MS/s IQ stream.

Edit ``ACTIVE_EXAMPLE`` or ``TEST_CONFIG`` below, then run::

    PYTHONPATH=software python -m dr47.hardware_wave_test
"""

from __future__ import annotations

from dataclasses import dataclass
import math
import time
from typing import Literal

import numpy as np

from .capabilities import PlaybackState
from .device import Dr47Device, rfdc_nco_plan_for_target
from .errors import DriverError


WaveformKind = Literal["sine", "gaussian_sine"]
PlaybackMode = Literal["one_shot", "continuous", "triggered"]
SyncRole = Literal["master", "slave"]
SyncMode = Literal["external", "self_test"]


@dataclass
class HardwareWaveTestConfig:
    """Editable real-board test configuration.

    ``sample_rate_ghz=0.4`` means 400 MS/s.  ``frequency_ghz`` is the RF
    output target; ``baseband_frequency_ghz`` is an optional small complex
    envelope detuning and must stay within the 200 MHz complex Nyquist band.
    """

    ip: str = "169.254.32.1"
    port: int = 1234
    udp_interface: str = "enp225s0f1"
    udp_source_ip: str = "169.254.250.11"
    timeout_s: float = 1.0
    retries: int = 2
    duration_ns: float = 100.0
    sample_rate_ghz: float = 0.4
    frequency_ghz: float = 1.0
    nco_frequency_ghz: float | None = None
    baseband_frequency_ghz: float = 0.0
    waveform: WaveformKind = "sine"
    amplitude: float = 0.5
    gain: float = 0.2
    mode: PlaybackMode = "one_shot"
    # XS20 is the dedicated SYNC port.  ``self_test`` is an explicit test
    # bypass for a single board and does not generate a fake SYNC pulse.
    sync_role: SyncRole = "slave"
    sync_mode: SyncMode = "self_test"
    # In triggered mode, emit_trigger() drives XS18.  With an XS18 -> XS19
    # cable this exercises the physical trigger input path on the same board.
    external_trigger_loopback: bool = True
    sync_before_trigger: bool = False
    settle_s: float = 0.5
    hold_s: float = 0.5
    trigger_count: int = 4
    trigger_interval_s: float = 0.5
    keep_running: bool = False
    abort_existing: bool = True


# Four ready-to-run examples.  Select one by changing ACTIVE_EXAMPLE, or
# replace TEST_CONFIG with a HardwareWaveTestConfig edited for your setup.
EXAMPLES: dict[str, HardwareWaveTestConfig] = {
    # 1. 100 ns, 1 GHz sine, one shot.
    "one_shot_1ghz_sine": HardwareWaveTestConfig(
        duration_ns=100.0, frequency_ghz=1.0, waveform="sine", mode="one_shot", hold_s=0.5
    ),
    # 2. 60 ns, 1.79 GHz Gaussian sine on XY CH1, one shot.
    "one_shot_1p79ghz_gaussian_xy": HardwareWaveTestConfig(
        duration_ns=60.0, frequency_ghz=1.79, waveform="gaussian_sine", mode="one_shot", hold_s=0.5
    ),
    # 3. Continuous 2 GHz sine wave.
    "continuous_2ghz_sine": HardwareWaveTestConfig(
        duration_ns=100.0, frequency_ghz=2.0, waveform="sine", mode="continuous", hold_s=60.0
    ),
    # 4. 120 ns, 1.5 GHz Gaussian sine.  The loop waits for a trigger before
    # each playback; the smoke test sends trigger_count software triggers.
    "triggered_1p5ghz_gaussian_xy": HardwareWaveTestConfig(
        duration_ns=120.0,
        frequency_ghz=1.5,
        waveform="gaussian_sine",
        mode="triggered",
        sync_role="slave",
        sync_mode="self_test",
        external_trigger_loopback=True,
        trigger_count=4,
        trigger_interval_s=0.5,
        hold_s=0.5,
    ),
}

ACTIVE_EXAMPLE = "one_shot_1ghz_sine"
TEST_CONFIG = EXAMPLES[ACTIVE_EXAMPLE]


def sample_count_for_duration(duration_ns: float, sample_rate_ghz: float) -> int:
    """Return the nearest complex-IQ sample count for a duration in ns."""

    duration = float(duration_ns)
    rate = float(sample_rate_ghz)
    if not math.isfinite(duration) or duration <= 0.0:
        raise ValueError("duration_ns must be positive")
    if not math.isfinite(rate) or rate <= 0.0:
        raise ValueError("sample_rate_ghz must be positive")
    return max(1, int(round(duration * rate)))


def _validate_waveform_inputs(
    duration_ns: float, frequency_ghz: float, sample_rate_ghz: float, amplitude: float
) -> int:
    count = sample_count_for_duration(duration_ns, sample_rate_ghz)
    if not math.isfinite(float(amplitude)) or not 0.0 < float(amplitude) <= 1.0:
        raise ValueError("amplitude must be in (0, 1]")
    if not math.isfinite(float(frequency_ghz)):
        raise ValueError("baseband_frequency_ghz must be finite")
    nyquist = abs(float(sample_rate_ghz)) / 2.0
    if abs(float(frequency_ghz)) > nyquist:
        raise ValueError(
            f"baseband_frequency_ghz must be within +/-{nyquist:g} GHz for "
            f"sample_rate_ghz={sample_rate_ghz:g}"
        )
    return count


def make_iq_sine(
    duration_ns: float,
    frequency_ghz: float,
    sample_rate_ghz: float,
    amplitude: float,
) -> np.ndarray:
    """Return an ``(N, 2)`` little-endian int16 I/Q sine envelope."""

    count = _validate_waveform_inputs(duration_ns, frequency_ghz, sample_rate_ghz, amplitude)
    sample_index = np.arange(count, dtype=np.float64)
    # GHz * ns is cycles, so this expression avoids an implicit Hz conversion
    # in the user-facing waveform helper.
    phase = 2.0 * np.pi * float(frequency_ghz) * sample_index / float(sample_rate_ghz)
    scale = min(32767.0, float(amplitude) * 32767.0)
    return np.column_stack((np.cos(phase) * scale, np.sin(phase) * scale)).astype("<i2")


def make_gaussian_iq_sine(
    duration_ns: float,
    frequency_ghz: float,
    sample_rate_ghz: float,
    amplitude: float,
    sigma_fraction: float = 0.22,
) -> np.ndarray:
    """Return a Gaussian-windowed complex sine envelope as int16 IQ."""

    count = _validate_waveform_inputs(duration_ns, frequency_ghz, sample_rate_ghz, amplitude)
    if not 0.0 < float(sigma_fraction):
        raise ValueError("sigma_fraction must be positive")
    sample_index = np.arange(count, dtype=np.float64)
    center = (count - 1) / 2.0
    sigma = max(0.5, float(sigma_fraction) * max(1, count))
    envelope = np.exp(-0.5 * ((sample_index - center) / sigma) ** 2)
    phase = 2.0 * np.pi * float(frequency_ghz) * sample_index / float(sample_rate_ghz)
    scale = min(32767.0, float(amplitude) * 32767.0)
    return np.column_stack((envelope * np.cos(phase) * scale, envelope * np.sin(phase) * scale)).astype("<i2")


def make_iq_waveform(config: HardwareWaveTestConfig) -> np.ndarray:
    """Generate the configured baseband IQ waveform."""

    if config.waveform == "sine":
        return make_iq_sine(
            config.duration_ns,
            config.baseband_frequency_ghz,
            config.sample_rate_ghz,
            config.amplitude,
        )
    if config.waveform == "gaussian_sine":
        return make_gaussian_iq_sine(
            config.duration_ns,
            config.baseband_frequency_ghz,
            config.sample_rate_ghz,
            config.amplitude,
        )
    raise ValueError(f"unsupported waveform kind: {config.waveform!r}")


def make_trigger_sequence(sample_count: int) -> np.ndarray:
    """Build a looping WAVEINS-compatible sequence that waits per trigger."""

    count = int(sample_count)
    if count <= 0 or count > 0xFFFF:
        raise ValueError("sample_count must be in 1..65535")
    # LS(count=0) means an infinite top-level loop.  TR blocks at the start of
    # each iteration, DI plays the uploaded wave, and LE returns to TR.
    return np.asarray(
        [
            [0, count, 0, 0x0800],  # LS, infinite loop
            [0, count, 0, 0x4000],  # TR, wait for the next trigger
            [0, count, 0, 0x0000],  # DI, play CH1 waveform
            [0, count, 0, 0x1000],  # LE
            [0, count, 0, 0x8000],  # ST (translated to WAVEINS END)
        ],
        dtype="<u2",
    )


def _sleep_for_mode(config: HardwareWaveTestConfig) -> None:
    pulse_s = max(float(config.duration_ns) * 1e-9, 1e-6)
    if config.mode == "continuous":
        time.sleep(max(0.0, float(config.hold_s)))
    elif config.mode == "one_shot":
        time.sleep(max(float(config.hold_s), pulse_s + max(0.0, float(config.settle_s))))
    else:
        time.sleep(max(0.0, float(config.hold_s)))


def run(config: HardwareWaveTestConfig = TEST_CONFIG) -> int:
    """Run one configured real-board example and return a process status."""

    if config.mode not in {"one_shot", "continuous", "triggered"}:
        raise ValueError(f"unsupported playback mode: {config.mode!r}")
    iq = make_iq_waveform(config)
    sample_count = int(iq.shape[0])
    plan = rfdc_nco_plan_for_target(config.frequency_ghz)
    nco_frequency_ghz = float(plan["nco_ghz"] if config.nco_frequency_ghz is None else config.nco_frequency_ghz)
    nyquist_zone = int(plan["nyquist_zone"] if config.nco_frequency_ghz is None else 1)
    device = Dr47Device(
        ip=config.ip,
        port=config.port,
        timeout_s=config.timeout_s,
        udp_interface=config.udp_interface,
        udp_source_ip=config.udp_source_ip,
        retries=config.retries,
        batch_mode=True,
    )
    try:
        print(f"connecting to {config.ip}:{config.port} via {config.udp_interface or 'default route'}")
        device.connect()
        initial_status = device.status(refresh=False)
        print(f"HELLO/STATUS: {initial_status}")
        if initial_status.state is not PlaybackState.IDLE:
            if not config.abort_existing:
                raise DriverError(
                    f"board is already {initial_status.state.value}; set TEST_CONFIG.abort_existing=True "
                    "or stop the current playback before starting a new test"
                )
            print(f"existing playback is {initial_status.state.value}; sending ABORT_MUTE first")
            device.abort_mute()
            cleared_status = device.status(refresh=False)
            print(f"existing playback stopped: {cleared_status.state.value}")
            if cleared_status.state is not PlaybackState.IDLE:
                raise DriverError(f"board did not return to IDLE after ABORT_MUTE: {cleared_status.state.value}")

        device.set_sync_role(config.sync_role)
        device.set_sync_mode(config.sync_mode)
        print(f"SYNC configured: role={config.sync_role}, mode={config.sync_mode}")

        if config.sync_before_trigger:
            if config.sync_role != "master" or config.sync_mode != "external":
                raise DriverError("sync_before_trigger requires sync_role='master' and sync_mode='external'")
            device.sync(epoch=1)
            print("SYNC emitted on XS20 (single pulse)")

        # The public method receives GHz; it converts to RFCTRL2's integer Hz
        # internally.  The baseband stream stays at DC for these RF examples.
        device.set_xy_nco_frequency(1, nco_frequency_ghz)
        if nyquist_zone != 1:
            device.apply_rfdc_config(nyquist_zone={1: nyquist_zone}, channel_mask=0x01)
        device.set_gain("xy", 1, config.gain, gain_type="norm")
        device.set_qc_on_off("xy", 1, "on")
        rfdc_result = device.commit()
        print(f"RFDC config committed: {rfdc_result!r} (target={config.frequency_ghz:g} GHz)")

        sequences = None
        if config.mode == "triggered":
            sequences = {1: make_trigger_sequence(sample_count)}
        upload = device.upload_waveforms(
            {1: iq},
            channel_sequences=sequences,
            wave_formats={1: "iq_matrix"},
            auto_start=False,
            loop=config.mode == "continuous",
        )
        print(f"waveform uploaded: {upload}")
        time.sleep(max(0.0, float(config.settle_s)))
        device.arm(channel_mask=0x01)
        print(f"ARM accepted: {device.status(refresh=False)}")

        if config.mode == "triggered":
            count = max(1, int(config.trigger_count))
            for index in range(count):
                if index:
                    time.sleep(max(0.0, float(config.trigger_interval_s)))
                if config.external_trigger_loopback:
                    device.emit_trigger()
                    action = "XS18 emitted -> XS19 input"
                else:
                    device.trigger()
                    action = "local software trigger"
                print(f"TRIGGER sent ({index + 1}/{count}, {action}): {device.status(refresh=False)}")
        else:
            device.trigger()
            print(f"TRIGGER accepted: {device.status(refresh=False)}")
        _sleep_for_mode(config)
        if not config.keep_running:
            device.abort_mute()
            print(f"ABORT_MUTE accepted: {device.status(refresh=False)}")
        return 0
    except DriverError as exc:
        print(f"driver error: {type(exc).__name__}: {exc}")
        return 2
    finally:
        device.close()


def main() -> int:
    return run(TEST_CONFIG)


if __name__ == "__main__":
    raise SystemExit(main())


__all__ = [
    "HardwareWaveTestConfig", "EXAMPLES", "ACTIVE_EXAMPLE", "TEST_CONFIG",
    "sample_count_for_duration", "make_iq_sine", "make_gaussian_iq_sine",
    "make_iq_waveform", "make_trigger_sequence", "run", "main",
]
