"""Generate the checked-in FIR coefficient ROM and report its numeric limits."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np

TAPS = 16
PHASES = 64
FRACTION_BITS = 16
SAMPLE_RATE_HZ = 400e6
KAISER_BETA = 8.6


def coefficient_table() -> np.ndarray:
    taps = np.arange(TAPS)
    window = np.kaiser(TAPS, KAISER_BETA)
    rows = []
    for phase in range(PHASES):
        kernel = np.sinc(taps - (7.0 + phase / PHASES)) * window
        kernel /= kernel.sum()
        quantized = np.rint(kernel * (1 << FRACTION_BITS)).astype(np.int64)
        quantized[np.argmax(np.abs(kernel))] += (1 << FRACTION_BITS) - quantized.sum()
        if np.any(quantized < -(1 << 17)) or np.any(quantized >= (1 << 17)):
            raise ValueError("coefficient exceeds signed 18-bit Q2.16")
        rows.append(quantized)
    return np.asarray(rows)


def verilog_rom(table: np.ndarray) -> str:
    lines = [
        "`timescale 1ns/1ps",
        "",
        "// Generated by tests/generate_fractional_delay_coeffs.py.",
        "// 16 taps, 64 phases, signed Q2.16; DC sum is exactly 65536.",
        "// Nominal group delay: 7 + phase/64 complex samples at 400 MS/s.",
        f"// Kaiser beta={KAISER_BETA}; coefficient k occupies [18*k +: 18].",
        "module iq_fractional_delay_coeffs (",
        "    input wire [5:0] phase,",
        "    output reg [287:0] coefficients",
        ");",
        "  always @* begin",
        "    case (phase)",
    ]
    for phase, row in enumerate(table):
        packed = sum((int(value) & 0x3FFFF) << (18 * tap) for tap, value in enumerate(row))
        lines.append(f"      6'd{phase}: coefficients = 288'h{packed:072x};")
    lines.extend([
        "      default: coefficients = 288'd0;",
        "    endcase",
        "  end",
        "endmodule",
        "",
    ])
    return "\n".join(lines)


def metrics(table: np.ndarray) -> dict:
    taps = np.arange(TAPS)
    coeffs = table / float(1 << FRACTION_BITS)
    target_delay = 7 + np.arange(PHASES) / PHASES
    results = {}
    for bandwidth in (50, 100, 150, 180):
        omega = np.linspace(0, 2 * np.pi * bandwidth * 1e6 / SAMPLE_RATE_HZ, 8193)
        basis = np.exp(-1j * taps[:, None] * omega[None, :])
        response = coeffs @ basis
        weighted_response = (coeffs * taps) @ basis
        group_delay = np.real(weighted_response / response)
        delay_error_ps = (group_delay - target_delay[:, None]) / SAMPLE_RATE_HZ * 1e12
        gain_db = 20 * np.log10(np.abs(response))
        results[f"plus_minus_{bandwidth}_MHz"] = {
            "max_abs_group_delay_error_ps": float(np.max(np.abs(delay_error_ps))),
            "min_gain_db": float(gain_db.min()),
            "max_gain_db": float(gain_db.max()),
        }
    return {
        "taps": TAPS,
        "phases": PHASES,
        "coefficient_format": "signed 18-bit Q2.16, exact unity DC sum",
        "kaiser_beta": KAISER_BETA,
        "phase_step_ps": 1e12 / SAMPLE_RATE_HZ / PHASES,
        "maximum_l1_gain": float(np.max(np.sum(np.abs(coeffs), axis=1))),
        "bands": results,
        "scope": "Numeric FIR response only; excludes TDC, clocks, RFDC and analog measurement errors.",
    }


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", type=Path, help="write generated Verilog ROM")
    parser.add_argument("--check", type=Path, help="verify ROM matches this generator")
    parser.add_argument("--report", type=Path, help="write numeric response report")
    args = parser.parse_args()
    table = coefficient_table()
    rom = verilog_rom(table)
    if args.write:
        args.write.parent.mkdir(parents=True, exist_ok=True)
        args.write.write_text(rom, encoding="ascii")
    if args.check and args.check.read_text(encoding="ascii") != rom:
        raise SystemExit("coefficient ROM does not match generator")
    report = json.dumps(metrics(table), indent=2) + "\n"
    if args.report:
        args.report.parent.mkdir(parents=True, exist_ok=True)
        args.report.write_text(report, encoding="ascii")
    print(report, end="")


if __name__ == "__main__":
    main()
