import unittest
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
SCRIPTS = REPO_ROOT / "hardware" / "vivado" / "scripts"
MAKEFILE = REPO_ROOT / "Makefile"
RFDC_CHISEL = REPO_ROOT / "hardware" / "chisel" / "rfdc" / "src" / "elaborate.scala"


class VivadoBuildOptionsTests(unittest.TestCase):
    def test_ila_depth_is_low_and_overridable(self):
        for script_name in ("ila_dac_axis.tcl", "ila_s_axi_01.tcl", "ila_udp_ddr.tcl"):
            script = (SCRIPTS / script_name).read_text(encoding="utf-8", errors="ignore")
            self.assertIn("build_option_get ILA_DEPTH 1024", script)
            self.assertIn("CONFIG.C_DATA_DEPTH ${ila_data_depth}", script)
            self.assertNotIn("CONFIG.C_DATA_DEPTH {4096}", script)

    def test_impl_reuses_completed_ooc_runs(self):
        script = (SCRIPTS / "run_impl.tcl").read_text(encoding="utf-8", errors="ignore")
        self.assertIn("skipping duplicate synthesis", script)
        self.assertIn("ooc_run_complete ${rfdc_run}", script)
        self.assertIn("ooc_run_complete ${ddr_run}", script)

    def test_impl_supports_fast_balanced_and_aggressive_profiles(self):
        script = (SCRIPTS / "run_impl.tcl").read_text(encoding="utf-8", errors="ignore")
        self.assertIn("build_option_get IMPL_MODE auto", script)
        self.assertIn("set impl_profiles [list balanced aggressive]", script)
        self.assertIn("set place_directive Quick", script)
        self.assertIn("ExtraNetDelay_high", script)
        self.assertIn("AggressiveExplore", script)
        self.assertIn('string match "*Complete*"', script)

    def test_makefile_exposes_project_reuse_build(self):
        makefile = MAKEFILE.read_text(encoding="utf-8", errors="ignore")
        self.assertIn("hardware-fast:", makefile)
        self.assertIn("TARGET=$(TARGET) ./build.sh", makefile)
        # The current entry also passes ARTIFACT_DIR/Vivado isolation variables
        # between TARGET and the script; check the behavior rather than an
        # exact command-line ordering.
        self.assertIn("TARGET=$(TARGET)", makefile)
        self.assertIn("./build.sh --clean", makefile)

    def test_rfdc_reference_clock_is_not_overridden_after_chisel_generation(self):
        create_project = (SCRIPTS / "create_project.tcl").read_text(encoding="utf-8", errors="ignore")
        chisel = RFDC_CHISEL.read_text(encoding="utf-8", errors="ignore")

        self.assertNotIn("DAC2_Refclk_Freq {133.333}", create_project)
        self.assertIn('CONFIG.DAC2_Refclk_Freq {128.000}', chisel)
        self.assertIn("DAC2_Refclk_Freq is generated by Chisel", create_project)

    def test_xxv_reference_checkpoint_uses_isolated_project_directory(self):
        reference = (SCRIPTS / "reference_xxv_dcp.tcl").read_text(encoding="utf-8", errors="ignore")
        synth = (SCRIPTS / "run_synth.tcl").read_text(encoding="utf-8", errors="ignore")

        self.assertIn("proc restore_reference_xxv_dcp {vivado_dir proj_dir target", reference)
        self.assertIn('"${proj_dir}/work/ip/xxv_ethernet_1/xxv_ethernet.dcp"', reference)
        self.assertIn("XXV_REFERENCE_DCP", reference)
        self.assertIn("restore_reference_xxv_dcp ${vivado_dir} ${proj_dir} ${target} ${proj_name}", synth)
        self.assertNotIn('"${vivado_dir}/work/ip/xxv_ethernet_1/xxv_ethernet.dcp"', reference)

        create_project = (SCRIPTS / "create_project.tcl").read_text(encoding="utf-8", errors="ignore")
        self.assertIn("create_fileset -blockset xxv_ethernet", create_project)
        self.assertIn("add_files -fileset ${xxv_fileset} -norecurse ${xxv_xci}", create_project)

    def test_master_trigger_launch_is_atomic_with_xs18_request(self):
        top = (REPO_ROOT / "hardware" / "vivado" / "src" / "Top.v").read_text(
            encoding="utf-8", errors="ignore"
        )
        self.assertIn("wire rfctrl2_master_launch_pulse", top)
        self.assertIn("sync_link_ready_ddr &&", top)
        self.assertIn("sync_role_master_ddr;", top)
        self.assertIn(
            ".trigger_request_ddr(rfctrl2_emit_trigger_pulse |\n"
            "                           rfctrl2_master_launch_pulse)",
            top,
        )
        self.assertNotIn("        ch4.\n", top)


if __name__ == "__main__":
    unittest.main()
