import unittest
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
SCRIPTS = REPO_ROOT / "hardware" / "vivado" / "scripts"
MAKEFILE = REPO_ROOT / "Makefile"
RFDC_CHISEL = REPO_ROOT / "hardware" / "chisel" / "rfdc" / "src" / "elaborate.scala"


class VivadoBuildOptionsTests(unittest.TestCase):
    def test_ila_depth_is_low_and_overridable(self):
        for script_name in ("ila_dac_axis.tcl", "ila_s_axi_01.tcl", "ila_udp_ddr.tcl"):
            script = (SCRIPTS / script_name).read_text(encoding="utf-8", errors="ignore")
            self.assertIn("build_option_get ILA_DEPTH 1024", script)
            self.assertIn("CONFIG.C_DATA_DEPTH ${ila_data_depth}", script)
            self.assertNotIn("CONFIG.C_DATA_DEPTH {4096}", script)

    def test_impl_reuses_completed_ooc_runs(self):
        script = (SCRIPTS / "run_impl.tcl").read_text(encoding="utf-8", errors="ignore")
        self.assertIn("skipping duplicate synthesis", script)
        self.assertIn("ooc_run_complete ${rfdc_run}", script)
        self.assertIn("ooc_run_complete ${ddr_run}", script)

    def test_impl_supports_fast_balanced_and_aggressive_profiles(self):
        script = (SCRIPTS / "run_impl.tcl").read_text(encoding="utf-8", errors="ignore")
        self.assertIn("build_option_get IMPL_MODE auto", script)
        self.assertIn("set impl_profiles [list balanced aggressive]", script)
        self.assertIn("set place_directive Quick", script)
        self.assertIn("ExtraNetDelay_high", script)
        self.assertIn("AggressiveExplore", script)
        self.assertIn('string match "*Complete*"', script)

    def test_makefile_exposes_project_reuse_build(self):
        makefile = MAKEFILE.read_text(encoding="utf-8", errors="ignore")
        self.assertIn("hardware-fast:", makefile)
        self.assertIn("TARGET=$(TARGET) ./build.sh", makefile)
        # The current entry also passes ARTIFACT_DIR/Vivado isolation variables
        # between TARGET and the script; check the behavior rather than an
        # exact command-line ordering.
        self.assertIn("TARGET=$(TARGET)", makefile)
        self.assertIn("./build.sh --clean", makefile)

    def test_production_bitstream_targets_do_not_require_ila_probes(self):
        makefile = MAKEFILE.read_text(encoding="utf-8", errors="ignore")
        self.assertIn("custom_xczu47dr_waveform.xsa", makefile)
        self.assertIn("custom_xczu47dr_waveform.elf", makefile)
        self.assertIn("ALLOWED_TARGETS := custom_xczu47dr_waveform", makefile)
        self.assertNotIn("bitstream-slave-trigout", makefile)
        self.assertNotIn("custom_xczu47dr_master", makefile)
        self.assertNotIn("custom_xczu47dr_slave", makefile)

    def test_ddr_mask_bus_has_top_level_pod12_constraint(self):
        xdc = (REPO_ROOT / "hardware" / "vivado" / "xdc" / "custom_xczu47dr_minimal.xdc").read_text(
            encoding="utf-8", errors="ignore"
        )
        self.assertIn("IOSTANDARD POD12_DCI [get_ports {c0_ddr4_dq[*] c0_ddr4_dm_n[*]}]", xdc)
        self.assertIn("IOSTANDARD DIFF_POD12_DCI", xdc)
        self.assertIn("IOSTANDARD SSTL12_DCI", xdc)
        self.assertIn("IOSTANDARD DIFF_SSTL12_DCI", xdc)
        self.assertIn("IOSTANDARD DIFF_SSTL12", xdc)
        self.assertIn("generated DDR4 IP's electrical XDC is scoped", xdc)
        self.assertNotIn("sync_trigger_link_i/sync_role_i/sync_in_sync_reg", xdc)

    def test_rfdc_reference_clock_is_not_overridden_after_chisel_generation(self):
        create_project = (SCRIPTS / "create_project.tcl").read_text(encoding="utf-8", errors="ignore")
        chisel = RFDC_CHISEL.read_text(encoding="utf-8", errors="ignore")

        self.assertNotIn("DAC2_Refclk_Freq {133.333}", create_project)
        self.assertIn('CONFIG.DAC2_Refclk_Freq {128.000}', chisel)
        self.assertIn("DAC2_Refclk_Freq is generated by Chisel", create_project)

    def test_xxv_ip_uses_project_managed_xci_flow(self):
        create_project = (SCRIPTS / "create_project.tcl").read_text(encoding="utf-8", errors="ignore")
        synth = (SCRIPTS / "run_synth.tcl").read_text(encoding="utf-8", errors="ignore")
        impl = (SCRIPTS / "run_impl.tcl").read_text(encoding="utf-8", errors="ignore")
        manual_entry = (SCRIPTS / "run_impl_manual.tcl").read_text(encoding="utf-8", errors="ignore")

        # The managed XCI must be in the normal project source set so Vivado
        # carries its provenance and scoped constraints into link_design.
        self.assertIn("read_ip ${xxv_xci}", create_project)
        self.assertIn("USED_IN_IMPLEMENTATION true", create_project)
        self.assertIn("generate_synth_checkpoint true", create_project)
        self.assertNotIn("create_fileset -blockset xxv_ethernet", create_project)
        self.assertNotIn("add_files -fileset ${xxv_fileset}", create_project)

        # A raw cell-level DCP injection was the source of the old provenance
        # and GT-port ownership warnings; the production flow must not use it.
        self.assertIn("Expected exactly one managed XXV Ethernet XCI", synth)
        self.assertIn("Expected exactly one managed XXV Ethernet XCI", impl)
        self.assertIn("prepare_reference_xxv_ooc_run", synth)
        self.assertIn("create_ip_run", (SCRIPTS / "reference_xxv_dcp.tcl").read_text(encoding="utf-8", errors="ignore"))
        self.assertIn("restore_reference_xxv_dcp", synth)
        self.assertIn("prepare_reference_xxv_ooc_run", impl)
        bitstream = (SCRIPTS / "run_bitstream.tcl").read_text(encoding="utf-8", errors="ignore")
        self.assertIn("restore_reference_xxv_dcp", bitstream)
        self.assertNotIn("read_checkpoint -cell", impl)
        self.assertIn("run_impl.tcl", manual_entry)

    def test_single_board_waveform_has_no_master_trigger_hierarchy(self):
        top = (REPO_ROOT / "hardware" / "vivado" / "src" / "Top.v").read_text(
            encoding="utf-8", errors="ignore"
        )
        # The waveform target is single-board only.  The retired sync-trigger
        # instance must not remain as an alternate playback admission path.
        self.assertIn("assign sync_link_ready = 1'b0;", top)
        self.assertIn("assign trigger_link_out = 1'b0;", top)
        self.assertNotIn("sync_trigger_link_i", top)
        self.assertNotIn("dac_trigger_emitter_i", top)

    def test_waveform_playback_wires_have_explicit_widths(self):
        top = (REPO_ROOT / "hardware" / "vivado" / "src" / "Top.v").read_text(
            encoding="utf-8", errors="ignore"
        )
        self.assertIn("wire new_output_first_transfer;", top)
        self.assertIn("wire new_prefetch_safe_ddr;", top)
        self.assertIn("waveform_playback_path waveform_playback_path_i", top)

    def test_waveform_writer_uses_ddr_state_shadow_not_dac_state_bus(self):
        top = (REPO_ROOT / "hardware" / "vivado" / "src" / "Top.v").read_text(
            encoding="utf-8", errors="ignore"
        )
        self.assertIn("wave_playback_state_ddr", top)
        self.assertIn("playback_state(wave_playback_state_ddr)", top)
        self.assertNotIn("playback_state(wave_playback_state)", top)

    def test_waveform_trigger_uses_dac_domain_capture(self):
        top = (REPO_ROOT / "hardware" / "vivado" / "src" / "Top.v").read_text(
            encoding="utf-8", errors="ignore"
        )
        self.assertNotIn("waveform_trigger_cdc waveform_trigger_cdc_i", top)
        self.assertIn("waveform_trigger_cdc u_trigger", (REPO_ROOT / "hardware" / "vivado" / "src" / "waveform_playback_path.v").read_text(encoding="utf-8", errors="ignore"))
        self.assertIn("assign TRIG_1 = new_output_first_transfer;", top)
        self.assertIn("wire [7:0] rfdc_all_valid", top)

    def test_waveform_target_excludes_retired_playback_rtl_and_cache(self):
        create_project = (SCRIPTS / "create_project.tcl").read_text(encoding="utf-8", errors="ignore")
        top = (REPO_ROOT / "hardware" / "vivado" / "src" / "Top.v").read_text(
            encoding="utf-8", errors="ignore"
        )
        for retired in (
            "udp_waveform_ddr_writer.v",
            "udp64_to_axis128_instr.v",
        ):
            self.assertIn(retired, create_project)
        self.assertNotIn("module replay_cache_ram", top)
        self.assertNotIn("replay_ram_ch1_i", top)
        self.assertNotIn("replay_cache_ready_dac", top)

    def test_waveform_target_excludes_retired_sync_trigger_hierarchy(self):
        create_project = (SCRIPTS / "create_project.tcl").read_text(encoding="utf-8", errors="ignore")
        top = (REPO_ROOT / "hardware" / "vivado" / "src" / "Top.v").read_text(
            encoding="utf-8", errors="ignore"
        )
        for retired in (
            "sync_trigger_link.v",
            "dac_trigger_emitter.v",
            "dac_ext_trigger_capture.v",
            "dac_trigger_latency_probe.v",
        ):
            self.assertIn(retired, create_project)
        for retired_instance in (
            "sync_trigger_link_i",
            "dac_trigger_emitter_i",
            "dac_ext_trigger_capture_i",
            "dac_trigger_latency_probe_i",
        ):
            self.assertNotIn(retired_instance, top)

    def test_waveform_target_has_no_retired_sync_or_role_generics(self):
        target_config = (SCRIPTS / "target_config.tcl").read_text(encoding="utf-8", errors="ignore")
        create_project = (SCRIPTS / "create_project.tcl").read_text(encoding="utf-8", errors="ignore")

        # The only released target is a single-board waveform design.  These
        # generics selected the retired master/slave and XS20 trigger variants
        # and must not remain as hidden build controls.
        self.assertNotIn("IS_MASTER=", target_config)
        self.assertNotIn("XS20_TRIG_OUT=", target_config)
        self.assertNotIn("TRIG_EMIT_DAC=", target_config)
        self.assertNotIn("is_master_target", create_project)
        self.assertNotIn("is_slave_target", create_project)

    def test_pl_control_plane_has_no_retired_playback_commands(self):
        control = (REPO_ROOT / "hardware" / "vivado" / "src" / "pl_riscv_control_v1.v").read_text(
            encoding="utf-8", errors="ignore"
        )

        # WAVECTR0 owns playback admission.  The PL command shim may retain
        # RFDC/MTS/TDC diagnostics, but must not decode or emit the retired
        # RFCTRL2 ARM/START/TRIGGER/ABORT or synchronization-role commands.
        for retired in (
            "RF2_OP_ARM",
            "RF2_OP_START_AT",
            "RF2_OP_TRIGGER",
            "RF2_OP_ABORT_MUTE",
            "RF2_OP_SET_SYNC_ROLE",
            "RF2_OP_EMIT_TRIGGER",
            "rfctrl2_arm_pulse",
            "rfctrl2_trigger_pulse",
            "rfctrl2_abort_mute_pulse",
            "rfctrl2_set_sync_role_pulse",
            "rfctrl2_emit_trigger_pulse",
        ):
            self.assertNotIn(retired, control)
        # Epoch remains an independent RFDC/MTS diagnostic command.
        self.assertIn("RF2_OP_SYNC_EPOCH", control)

    def test_top_has_no_retired_playback_control_connection(self):
        top = (REPO_ROOT / "hardware" / "vivado" / "src" / "Top.v").read_text(
            encoding="utf-8", errors="ignore"
        )
        for retired in (
            "rfctrl2_arm_pulse",
            "rfctrl2_trigger_pulse",
            "rfctrl2_abort_mute_pulse",
            "rfctrl2_set_sync_role_pulse",
            "rfctrl2_emit_trigger_pulse",
        ):
            self.assertNotIn(retired, top)
        self.assertIn("waveform_playback_path waveform_playback_path_i", top)

    def test_async_cdc_fifo_busy_signals_stay_in_their_own_domains(self):
        for module_name in ("waveform_command_cdc.v", "waveform_descriptor_cdc.v"):
            text = (REPO_ROOT / "hardware" / "vivado" / "src" / module_name).read_text(encoding="utf-8", errors="ignore")
            self.assertNotIn("rd_busy_sync_wr", text, module_name)
            self.assertNotIn("wr_busy_sync_rd", text, module_name)
            self.assertIn("rd_rst_sync_wr", text, module_name)
            self.assertIn("fifo_rst_n", text, module_name)
            self.assertIn(".rst(!fifo_rst_n)", text, module_name)
            self.assertIn("assign wr_ready = wr_rst_n && !full && !wr_rst_busy;", text, module_name)
            self.assertIn("assign rd_valid = rd_rst_n && !empty && !rd_rst_busy;", text, module_name)

    def test_reference_xxv_dcp_is_revision_locked_before_build_use(self):
        reference = (SCRIPTS / "reference_xxv_dcp.tcl").read_text(encoding="utf-8", errors="ignore")
        self.assertIn("validate_reference_xxv_dcp", reference)
        self.assertIn("xxv_ethernet_v4_1_13", reference)
        self.assertIn("EXPECTED_XXV_DCP_SHA256", reference)

    def test_external_trigger_launch_has_no_fixed_dac_scheduler(self):
        top = (REPO_ROOT / "hardware" / "vivado" / "src" / "Top.v").read_text(
            encoding="utf-8", errors="ignore"
        )
        capture = (REPO_ROOT / "hardware" / "vivado" / "src" / "dac_ext_trigger_capture.v").read_text(
            encoding="utf-8", errors="ignore"
        )
        self.assertNotIn("TARGET_DAC_DELAY_CYCLES", top)
        self.assertNotIn("dac_trigger_scheduler", top)
        self.assertIn("assign trigger_pulse = accept;", capture)
        self.assertFalse((REPO_ROOT / "hardware" / "vivado" / "src" / "dac_trigger_scheduler.v").exists())


if __name__ == "__main__":
    unittest.main()
