// Parent RTL-synthesis declaration for the reference XXV Ethernet IP.
// The real implementation is supplied by the checked-in XCI/reference DCP.
// This is deliberately a uniquely named parent black box.  Using a distinct
// name prevents Vivado from auto-disabling it as a duplicate IP top.
(* black_box *) module xxv_ethernet_parent_blackbox (
    input wire gt_rxp_in_0,
    input wire gt_rxn_in_0,
    output wire gt_txp_out_0,
    output wire gt_txn_out_0,
    input wire gt_refclk_p,
    input wire gt_refclk_n,
    output wire tx_clk_out_0,
    input wire rx_core_clk_0,
    output wire rx_clk_out_0,
    input wire s_axi_aclk_0,
    input wire s_axi_aresetn_0,
    input wire [31:0] s_axi_awaddr_0,
    input wire s_axi_awvalid_0,
    output wire s_axi_awready_0,
    input wire [31:0] s_axi_wdata_0,
    input wire [3:0] s_axi_wstrb_0,
    input wire s_axi_wvalid_0,
    output wire s_axi_wready_0,
    output wire [1:0] s_axi_bresp_0,
    output wire s_axi_bvalid_0,
    input wire s_axi_bready_0,
    input wire [31:0] s_axi_araddr_0,
    input wire s_axi_arvalid_0,
    output wire s_axi_arready_0,
    output wire [31:0] s_axi_rdata_0,
    output wire [1:0] s_axi_rresp_0,
    output wire s_axi_rvalid_0,
    input wire s_axi_rready_0,
    input wire pm_tick_0,
    input wire rx_reset_0,
    output wire user_rx_reset_0,
    output wire rx_axis_tvalid_0,
    output wire [63:0] rx_axis_tdata_0,
    output wire rx_axis_tlast_0,
    output wire [7:0] rx_axis_tkeep_0,
    output wire rx_axis_tuser_0,
    output wire stat_rx_block_lock_0,
    input wire tx_reset_0,
    output wire user_tx_reset_0,
    output wire tx_axis_tready_0,
    input wire tx_axis_tvalid_0,
    input wire [63:0] tx_axis_tdata_0,
    input wire tx_axis_tlast_0,
    input wire [7:0] tx_axis_tkeep_0,
    input wire tx_axis_tuser_0,
    input wire [55:0] tx_preamblein_0,
    input wire ctl_tx_send_lfi_0,
    input wire ctl_tx_send_rfi_0,
    input wire ctl_tx_send_idle_0,
    input wire gtwiz_reset_tx_datapath_0,
    input wire gtwiz_reset_rx_datapath_0,
    input wire [2:0] txoutclksel_in_0,
    input wire [2:0] rxoutclksel_in_0,
    input wire qpllreset_in_0,
    output wire gt_refclk_out,
    input wire sys_reset,
    input wire dclk
);
endmodule
