#ifndef XCZU47DR_RFDC_XPARAMETERS_WRAPPER_H
#define XCZU47DR_RFDC_XPARAMETERS_WRAPPER_H

#include_next "xparameters.h"

#if defined(BOARD_CUSTOM_XCZU47DR)

#ifndef XPAR_XRFDC_NUM_INSTANCES
#define XPAR_XRFDC_NUM_INSTANCES 1U
#endif

#ifndef XPAR_XRFDC_0_DEVICE_ID
#define XPAR_XRFDC_0_DEVICE_ID 0U
#endif

#ifndef XPAR_XRFDC_0_BASEADDR
#if defined(XPAR_TOP_I_DESIGN_1_I_M_AXI_RFDC_BASEADDR)
#define XPAR_XRFDC_0_BASEADDR XPAR_TOP_I_DESIGN_1_I_M_AXI_RFDC_BASEADDR
#else
#define XPAR_XRFDC_0_BASEADDR 0xA0040000U
#endif
#endif

#ifndef XPAR_XRFDC_0_HIGHADDR
#if defined(XPAR_TOP_I_DESIGN_1_I_M_AXI_RFDC_HIGHADDR)
#define XPAR_XRFDC_0_HIGHADDR XPAR_TOP_I_DESIGN_1_I_M_AXI_RFDC_HIGHADDR
#else
#define XPAR_XRFDC_0_HIGHADDR 0xA007FFFFU
#endif
#endif

#ifndef XPAR_XRFDC_0_DEV_NAME
#define XPAR_XRFDC_0_DEV_NAME "rfdc_custom_xczu47dr_ip"
#endif

#endif

#endif
