`timescale 1ns/1ps

// Generated by tests/generate_fractional_delay_coeffs.py.
// 16 taps, 64 phases, signed Q2.16; DC sum is exactly 65536.
// Nominal group delay: 7 + phase/64 complex samples at 400 MS/s.
// Kaiser beta=8.6; coefficient k occupies [18*k +: 18].
module iq_fractional_delay_coeffs (
    input wire [5:0] phase,
    output reg [287:0] coefficients
);
  always @* begin
    case (phase)
      6'd0: coefficients = 288'h000000000000000000000000000000000000400000000000000000000000000000000000;
      6'd1: coefficients = 288'h000000003fffc8002affe6400dcff908040f3fe77fc990051bff78000d3fff00000c0000;
      6'd2: coefficients = 288'h000000006fff940054ffcc801b9ff200083a3fc17f95100a17fef2001a3ffe00001c0000;
      6'd3: coefficients = 288'hffffc0009fff5c007effb280297feae40c813f90bf62800ef7fe6e0026bffd00002bffff;
      6'd4: coefficients = 288'hffffc000cfff2800a8ff98c0375fe3bc10e33f52bf31d013b7fded00333ffc000037ffff;
      6'd5: coefficients = 288'hffffc000effef000d2ff7f00454fdc8c155e3f087f03301857fd6e003f7ffb100043ffff;
      6'd6: coefficients = 288'hffffc0011ffebc00fbff6540531fd55419f13eb23ed6901cd7fcf3004b7ffa20004fffff;
      6'd7: coefficients = 288'hffffc0014ffe880124ff4c0060efce201e9c3e4e7eac00212ffc7b00573ff940005fffff;
      6'd8: coefficients = 288'hffffc0017ffe54014dff32c06e8fc6ec235c3de0fe83702563fc0600627ff850006bfffe;
      6'd9: coefficients = 288'hffff80019ffe200174ff1a007c1fbfc028313d673e5d00296ffb95006d7ff7800073fffe;
      6'd10: coefficients = 288'hffff8001cffdf0019cff0180897fb89c2d183ce17e38a02d4ffb2900783ff6a0007ffffe;
      6'd11: coefficients = 288'hffff8001fffdbc01c2fee980969fb18832123c50be16603107fac000827ff5d0008bfffe;
      6'd12: coefficients = 288'hffff80021ffd9001e8fed240a38faa88371c3bb3fdf640348ffa5c008c3ff5100097fffe;
      6'd13: coefficients = 288'hffff80024ffd60020cfebb40b03fa3a03c353b0d3dd83037ebf9fc0095bff450009ffffe;
      6'd14: coefficients = 288'hffff80026ffd340230fea500bc9f9cd4415c3a5b7dbc403b17f9a1009ebff39000a7fffe;
      6'd15: coefficients = 288'hffff80028ffd080252fe8f40c89f9628468f399f3da2703e17f94b00a77ff2e000b3fffd;
      6'd16: coefficients = 288'hffff4002bffcdc0273fe7a40d45f8fa04bcc38d8fd8ac040dff8fa00af7ff24000bbfffd;
      6'd17: coefficients = 288'hffff4002dffcb40293fe6640dfaf8940511238087d7520437bf8ae00b6fff1a000c3fffd;
      6'd18: coefficients = 288'hffff4002fffc9002b1fe5300ea8f830c565f372ebd619045dff86700be3ff11000cbfffd;
      6'd19: coefficients = 288'hffff40031ffc6802cefe4080f4ff7d0c5bb2364bbd50104813f82500c4bff09000d3fffd;
      6'd20: coefficients = 288'hffff40032ffc4802eafe2f00feff773c6109355f3d40b04a13f7e900cafff01000d7fffd;
      6'd21: coefficients = 288'hffff40034ffc280304fe1e81087f71a8666334697d33504bdff7b300d07fefa000dffffd;
      6'd22: coefficients = 288'hffff40036ffc08031cfe0f01116f6c546bbe336c3d27e04d77f78200d57fef3000e3fffd;
      6'd23: coefficients = 288'hffff40037ffbec0332fe008119cf673c71183266bd1e804edbf75700d9ffeed000ebfffd;
      6'd24: coefficients = 288'hffff40038ffbd40347fdf34121af626c76703158fd17105007f73100ddffee8000effffd;
      6'd25: coefficients = 288'hffff4003affbbc0359fde70128df5de47bc33044bd11905103f71100e13fee4000f3fffc;
      6'd26: coefficients = 288'hffff0003bffba8036afddc012f7f59a881112f297d0df051c7f6f700e3ffee0000f3fffc;
      6'd27: coefficients = 288'hffff0003cffb940379fdd201356f55c086582e073d0c305257f6e200e63fedd000f7fffc;
      6'd28: coefficients = 288'hffff0003cffb840386fdc9813abf522c8b962cddfd0c3052b7f6d400e7ffedb000fbfffc;
      6'd29: coefficients = 288'hffff0003dffb780391fdc2413f4f4ef090c82baf7d0e1052dff6cb00e93fed9000fbfffc;
      6'd30: coefficients = 288'hffff0003effb700399fdbc41433f4c0c95ef2a7bbd119052d7f6c700e9bfed8000fbfffc;
      6'd31: coefficients = 288'hffff0003effb6803a0fdb781465f498c9b072942bd16d0529ff6c900e9bfed8000fbfffc;
      6'd32: coefficients = 288'hffff0003effb6003a4fdb44148cf4770a0102804bd1dc05233f6d100e93fed8000fbfffc;
      6'd33: coefficients = 288'hffff0003effb6003a6fdb2414a7f45b4a50a26c1fd26305197f6de00e83feda000fbfffc;
      6'd34: coefficients = 288'hffff0003effb6003a6fdb1c14b5f4464a9ee257bfd303050cff6f100e67fedc000fbfffc;
      6'd35: coefficients = 288'hffff0003effb6403a4fdb2c14b7f4384aebd24323d3bc04fd3f70900e47fede000f7fffc;
      6'd36: coefficients = 288'hffff0003effb6c039ffdb5014adf430cb37722e5bd48b04eaff72600e1bfee1000f3fffc;
      6'd37: coefficients = 288'hffff0003dffb740398fdb881495f430cb81c21963d57004d5bf74800de7fee5000f3fffc;
      6'd38: coefficients = 288'hffff0003cffb80038ffdbdc1471f437cbca520447d66a04bdff77000dabfeea000effffc;
      6'd39: coefficients = 288'hffff0003cffb900384fdc441440f4464c1121ef0fd77904a37f79c00d67feef000ebfffd;
      6'd40: coefficients = 288'hffff4003bffba00377fdcc41401f45c4c5631d9c3d89b0486bf7cd00d1ffef5000e3fffd;
      6'd41: coefficients = 288'hffff4003affbb40367fdd5c13b6f47a0c99a1c463d9cf04673f80200ccbfefb000dffffd;
      6'd42: coefficients = 288'hffff40038ffbcc0355fde08135df49f8cdb01aefbdb150445bf83c00c73ff02000dbfffd;
      6'd43: coefficients = 288'hffff40037ffbe80341fdecc12f7f4cd4d1a51998fdc6a0421ff87a00c13ff0a000d3fffd;
      6'd44: coefficients = 288'hffff40035ffc04032bfdfa41284f502cd57c18427ddcf03fbff8bc00babff12000cbfffd;
      6'd45: coefficients = 288'hffff40034ffc240312fe0941204f5404d92e16ecbdf4303d3ff90200b3bff1a000c7fffd;
      6'd46: coefficients = 288'hffff40032ffc4402f8fe19c1177f5864dcba1597fe0c303aa3f94c00ac7ff24000bffffd;
      6'd47: coefficients = 288'hffff40030ffc6802dbfe2b810def5d48e0211444be250037ebf99900a4fff2d000b7fffd;
      6'd48: coefficients = 288'hffff4002effc9002bdfe3e81037f62b0e36312f33e3e803517f9e9009cfff37000affffd;
      6'd49: coefficients = 288'hffff4002cffcb8029dfe52c0f85f689ce67c11a3fe58a03227fa3d0094bff42000a3fffe;
      6'd50: coefficients = 288'hffff80029ffce4027afe6840ec5f6f10e96d10573e73502f27fa94008c3ff4d0009bfffe;
      6'd51: coefficients = 288'hffff80027ffd140256fe7f00dfaf760cec340f0d7e8e802c0ffaed00833ff5800093fffe;
      6'd52: coefficients = 288'hffff80025ffd440230fe9700d23f7d90eecf0dc73eaa2028e3fb49007a3ff6400087fffe;
      6'd53: coefficients = 288'hffff80022ffd740209feb000c41f8598f1420c84bec62025a7fba60070bff6f0007ffffe;
      6'd54: coefficients = 288'hffff8001fffda801e0feca40b53f8e28f3850b463ee270225ffc0600673ff7c00073fffe;
      6'd55: coefficients = 288'hffff8001cffde001b5fee540a5bf9740f59c0a0c7eff001f07fc68005d3ff8800067fffe;
      6'd56: coefficients = 288'hffff8001affe140189ff0180958fa0dcf78308d73f1bb01ba3fccb00537ff950005fffff;
      6'd57: coefficients = 288'hffffc0017ffe50015cff1ec084bfab00f93907a73f3880183bfd3000493ffa200053ffff;
      6'd58: coefficients = 288'hffffc0013ffe88012dff3cc0735fb5a4fac8067c7f555014c7fd95003efffaf00047ffff;
      6'd59: coefficients = 288'hffffc0010ffec400fdff5b80615fc0ccfc210557bf72301153fdfc0034bffbc0003bffff;
      6'd60: coefficients = 288'hffffc000dfff0000ccff7b404edfcc74fd4a0438ff8ef00dd7fe63002a3ffca00033ffff;
      6'd61: coefficients = 288'hffffc000afff40009aff9b803bdfd8a0fe4203207fab900a5ffeca001fbffd700027ffff;
      6'd62: coefficients = 288'h000000007fff800068ffbc80285fe544ff05020ebfc80006e7ff3200153ffe5000180000;
      6'd63: coefficients = 288'h000000003fffc00034ffde00146ff264ff9d0103ffe4200373ff99000abfff20000c0000;
      default: coefficients = 288'd0;
    endcase
  end
endmodule
