`timescale 1ns/1ps

// Deterministic board-to-board SYNC and Trigger link.
//
// Physical SYNC and Trigger events live in hmc_pl_clk, generated by HMC7044.
// DDR and PS PL clocks only create command toggles or consume status.  XS20
// and XS19 therefore never pass through the unrelated PS pl_clk before they
// affect HMC7044 or playback scheduling.
module sync_trigger_link #(
    parameter integer IS_MASTER = 1,
    parameter integer WAIT_CYCLES = 20000,
    parameter integer HIGH_CYCLES = 40,
    parameter integer TRIGGER_HIGH_CYCLES = 8,
    parameter integer MASTER_LAUNCH_DELAY_CYCLES = 7,
    parameter integer SLAVE_LAUNCH_DELAY_CYCLES = 3
) (
    input  wire ddr_clk,
    input  wire ddr_rst_n,
    input  wire pl_clk,
    input  wire pl_rst_n,
    input  wire hmc_pl_clk,
    input  wire hmc_pl_rst_n,
    input  wire sync_request_ddr,
    input  wire trigger_request_ddr,
    input  wire emit_trigger_request_ddr,
    input  wire sync_request_vio_pl,
    input  wire sync_in,
    input  wire trigger_in,
    input  wire dac_trigger_start,
    input  wire role_master,
    input  wire sync_bypass,
    input  wire playback_prepared,
    input  wire [5:0] firmware_ack_epoch,
    input  wire firmware_align_failed,
    output wire hmc_sync,
    output wire sync_link_out,
    output wire trigger_link_out,
    output wire role_trigger_raw,
    output wire trigger_event_toggle,
    // Asserted while trigger_event_toggle describes an XS19 (external) event
    // rather than a host command.  Updated at accept time, several hmc_pl_clk
    // cycles before the toggle flips, so a receiver that samples both with the
    // same synchronizer always pairs the toggle with settled data.
    output wire trigger_event_external,
    output wire sync_done,
    output wire sync_seen,
    output wire sync_link_ready,
    output wire [5:0] sync_event_epoch,
    output wire sync_align_busy,
    output wire sync_align_failed,
    output wire [5:0] sync_alignment_epoch,
    output wire trigger_in_seen,
    output wire trigger_accepted,
    output wire trigger_output_active,
    output wire [31:0] trigger_input_count,
    output wire [31:0] trigger_accepted_count,
    output wire [31:0] trigger_output_count,
    output wire [63:0] hmc_event_tick,
    output wire [63:0] sync_event_tick,
    output wire [63:0] trigger_capture_tick,
    output wire [63:0] trigger_launch_tick
);
  localparam integer TRIGGER_COUNT_WIDTH =
      (TRIGGER_HIGH_CYCLES <= 1) ? 1 : $clog2(TRIGGER_HIGH_CYCLES + 1);
  localparam integer LAUNCH_DELAY_MAX =
      (MASTER_LAUNCH_DELAY_CYCLES > SLAVE_LAUNCH_DELAY_CYCLES) ?
      MASTER_LAUNCH_DELAY_CYCLES : SLAVE_LAUNCH_DELAY_CYCLES;
  localparam integer LAUNCH_COUNT_WIDTH =
      (LAUNCH_DELAY_MAX <= 1) ? 1 : $clog2(LAUNCH_DELAY_MAX + 1);

  // DDR command toggles cannot be lost between unrelated clocks.
  reg sync_request_toggle_ddr;
  reg trigger_request_toggle_ddr;
  reg emit_trigger_toggle_ddr;
  always @(posedge ddr_clk or negedge ddr_rst_n) begin
    if (!ddr_rst_n) begin
      sync_request_toggle_ddr <= 1'b0;
      trigger_request_toggle_ddr <= 1'b0;
      emit_trigger_toggle_ddr <= 1'b0;
    end else begin
      if (sync_request_ddr)
        sync_request_toggle_ddr <= ~sync_request_toggle_ddr;
      if (trigger_request_ddr)
        trigger_request_toggle_ddr <= ~trigger_request_toggle_ddr;
      if (emit_trigger_request_ddr)
        emit_trigger_toggle_ddr <= ~emit_trigger_toggle_ddr;
    end
  end

  reg sync_vio_prev_pl;
  reg sync_vio_toggle_pl;
  always @(posedge pl_clk or negedge pl_rst_n) begin
    if (!pl_rst_n) begin
      sync_vio_prev_pl <= 1'b0;
      sync_vio_toggle_pl <= 1'b0;
    end else begin
      sync_vio_prev_pl <= sync_request_vio_pl;
      if (sync_request_vio_pl && !sync_vio_prev_pl)
        sync_vio_toggle_pl <= ~sync_vio_toggle_pl;
    end
  end

  // HMC PL_CLK domain command and configuration synchronizers.
  (* ASYNC_REG = "TRUE", SHREG_EXTRACT = "NO" *) reg [1:0] sync_request_hmc_sync;
  (* ASYNC_REG = "TRUE", SHREG_EXTRACT = "NO" *) reg [1:0] sync_vio_hmc_sync;
  (* ASYNC_REG = "TRUE", SHREG_EXTRACT = "NO" *) reg [1:0] trigger_request_hmc_sync;
  (* ASYNC_REG = "TRUE", SHREG_EXTRACT = "NO" *) reg [1:0] emit_trigger_hmc_sync;
  (* ASYNC_REG = "TRUE", SHREG_EXTRACT = "NO" *) reg [1:0] bypass_hmc_sync;
  (* ASYNC_REG = "TRUE", SHREG_EXTRACT = "NO" *) reg [1:0] ready_hmc_sync;
  (* ASYNC_REG = "TRUE", SHREG_EXTRACT = "NO" *) reg [1:0] playback_prepared_hmc_sync;
  reg sync_request_hmc_seen;
  reg sync_vio_hmc_seen;
  reg trigger_request_hmc_seen;
  reg emit_trigger_hmc_seen;
  reg sync_link_ready_reg;
  reg trigger_wait_rearm_hmc;
  reg trigger_seen_unprepared_hmc;

  wire sync_request_hmc_pulse =
      (sync_request_hmc_sync[1] != sync_request_hmc_seen) ||
      (sync_vio_hmc_sync[1] != sync_vio_hmc_seen);
  wire trigger_request_hmc_pulse =
      trigger_request_hmc_sync[1] != trigger_request_hmc_seen;
  wire emit_trigger_hmc_pulse =
      emit_trigger_hmc_sync[1] != emit_trigger_hmc_seen;
  wire sync_trigger_allowed_hmc = role_master || bypass_hmc_sync[1] || ready_hmc_sync[1];
  wire trigger_allowed_hmc = sync_trigger_allowed_hmc &&
                             playback_prepared_hmc_sync[1] &&
                             !trigger_wait_rearm_hmc;

  wire sync_done_hmc;
  wire sync_hmc_internal;
  wire sync_link_internal;
  sync_role_control #(
      .IS_MASTER(IS_MASTER),
      .WAIT_CYCLES(WAIT_CYCLES),
      .HIGH_CYCLES(HIGH_CYCLES)
  ) sync_role_i (
      .clk         (hmc_pl_clk),
      .rst_n       (hmc_pl_rst_n),
      .sync_request(sync_request_hmc_pulse),
      .sync_in     (sync_in),
      .role_master (role_master),
      .sync_bypass (bypass_hmc_sync[1]),
      .hmc_sync    (sync_hmc_internal),
      .slave_sync  (sync_link_internal),
      .sync_done   (sync_done_hmc)
  );

  // XS19 is sampled only in HMC PL_CLK.  A three-stage synchronizer gives
  // metastability protection; the external pulse is held for at least three
  // HMC clock cycles by the master output generator.
  (* ASYNC_REG = "TRUE", SHREG_EXTRACT = "NO" *) reg [2:0] trigger_in_hmc_sync;
  reg trigger_in_hmc_prev;
  reg trigger_event_toggle_hmc;
  reg trigger_event_external_hmc;
  reg trigger_event_pulse_hmc;
  reg trigger_in_seen_hmc;
  reg trigger_accepted_hmc;
  reg trigger_link_hmc;
  reg trigger_output_active_hmc;
  reg [TRIGGER_COUNT_WIDTH-1:0] trigger_high_count;
  reg launch_pending_hmc;
  reg [LAUNCH_COUNT_WIDTH-1:0] launch_count;
  reg [31:0] trigger_input_count_hmc;
  reg [31:0] trigger_accepted_count_hmc;
  reg [31:0] trigger_output_count_hmc;
  reg [63:0] hmc_tick_hmc;
  reg [63:0] sync_tick_hmc;
  reg [63:0] trigger_capture_tick_hmc;
  reg [63:0] trigger_launch_tick_hmc;
  reg sync_done_toggle_hmc;

  wire trigger_in_rise_hmc = trigger_in_hmc_sync[2] && !trigger_in_hmc_prev;
  // A local RFCTRL2 Trigger is valid on the master, or on a slave only when
  // the firmware explicitly selected bypass mode.  In external mode a slave
  // must remain driven by XS19, so a host Trigger command is rejected.
  wire local_trigger_accept_hmc =
      (role_master || bypass_hmc_sync[1]) &&
      trigger_request_hmc_pulse && trigger_allowed_hmc;
  wire external_trigger_accept_hmc = !role_master && trigger_in_rise_hmc && trigger_allowed_hmc;
  wire any_trigger_accept_hmc = local_trigger_accept_hmc || external_trigger_accept_hmc ||
                                (dac_trigger_start && trigger_allowed_hmc);

  always @(posedge hmc_pl_clk or negedge hmc_pl_rst_n) begin
    if (!hmc_pl_rst_n) begin
      sync_request_hmc_sync <= 2'b00;
      sync_vio_hmc_sync <= 2'b00;
      trigger_request_hmc_sync <= 2'b00;
      emit_trigger_hmc_sync <= 2'b00;
      bypass_hmc_sync <= 2'b00;
      ready_hmc_sync <= 2'b00;
      playback_prepared_hmc_sync <= 2'b00;
      sync_request_hmc_seen <= 1'b0;
      sync_vio_hmc_seen <= 1'b0;
      trigger_request_hmc_seen <= 1'b0;
      emit_trigger_hmc_seen <= 1'b0;
      trigger_in_hmc_sync <= 3'b000;
      trigger_in_hmc_prev <= 1'b0;
      trigger_event_toggle_hmc <= 1'b0;
      trigger_event_external_hmc <= 1'b0;
      trigger_event_pulse_hmc <= 1'b0;
      trigger_in_seen_hmc <= 1'b0;
      trigger_accepted_hmc <= 1'b0;
      trigger_link_hmc <= 1'b0;
      trigger_output_active_hmc <= 1'b0;
      trigger_high_count <= {TRIGGER_COUNT_WIDTH{1'b0}};
      launch_pending_hmc <= 1'b0;
      launch_count <= {LAUNCH_COUNT_WIDTH{1'b0}};
      trigger_input_count_hmc <= 32'd0;
      trigger_accepted_count_hmc <= 32'd0;
      trigger_output_count_hmc <= 32'd0;
      hmc_tick_hmc <= 64'd0;
      sync_tick_hmc <= 64'd0;
      trigger_capture_tick_hmc <= 64'd0;
      trigger_launch_tick_hmc <= 64'd0;
      sync_done_toggle_hmc <= 1'b0;
      trigger_wait_rearm_hmc <= 1'b0;
      trigger_seen_unprepared_hmc <= 1'b0;
    end else begin
      sync_request_hmc_sync <= {sync_request_hmc_sync[0], sync_request_toggle_ddr};
      sync_vio_hmc_sync <= {sync_vio_hmc_sync[0], sync_vio_toggle_pl};
      trigger_request_hmc_sync <= {trigger_request_hmc_sync[0], trigger_request_toggle_ddr};
      emit_trigger_hmc_sync <= {emit_trigger_hmc_sync[0], emit_trigger_toggle_ddr};
      bypass_hmc_sync <= {bypass_hmc_sync[0], sync_bypass};
      ready_hmc_sync <= {ready_hmc_sync[0], sync_link_ready_reg};
      playback_prepared_hmc_sync <= {playback_prepared_hmc_sync[0], playback_prepared};
      trigger_in_hmc_sync <= {trigger_in_hmc_sync[1:0], trigger_in};
      trigger_in_hmc_prev <= trigger_in_hmc_sync[2];
      hmc_tick_hmc <= hmc_tick_hmc + 1'b1;
      trigger_event_pulse_hmc <= 1'b0;
      trigger_in_seen_hmc <= trigger_in_rise_hmc;
      trigger_accepted_hmc <= 1'b0;

      // Consume at most one Trigger per PREPARED interval. The finite-frame
      // executor drops PREPARED while refilling and raises it again when the
      // same DDR record is ready for the next external Trigger.
      if (trigger_wait_rearm_hmc) begin
        if (!playback_prepared_hmc_sync[1]) begin
          trigger_seen_unprepared_hmc <= 1'b1;
        end else if (trigger_seen_unprepared_hmc) begin
          trigger_wait_rearm_hmc <= 1'b0;
          trigger_seen_unprepared_hmc <= 1'b0;
        end
      end

      if (sync_request_hmc_pulse) begin
        sync_request_hmc_seen <= sync_request_hmc_sync[1];
        sync_vio_hmc_seen <= sync_vio_hmc_sync[1];
      end
      if (trigger_request_hmc_pulse)
        trigger_request_hmc_seen <= trigger_request_hmc_sync[1];
      if (emit_trigger_hmc_pulse)
        emit_trigger_hmc_seen <= emit_trigger_hmc_sync[1];
      if (sync_done_hmc) begin
        sync_done_toggle_hmc <= ~sync_done_toggle_hmc;
        sync_tick_hmc <= hmc_tick_hmc;
      end

      if (trigger_high_count != {TRIGGER_COUNT_WIDTH{1'b0}}) begin
        trigger_high_count <= trigger_high_count - 1'b1;
        trigger_link_hmc <= 1'b1;
      end else begin
        trigger_link_hmc <= 1'b0;
      end
      trigger_output_active_hmc <= trigger_link_hmc;

      if (trigger_in_rise_hmc)
        trigger_input_count_hmc <= trigger_input_count_hmc + 1'b1;
      if (any_trigger_accept_hmc) begin
        trigger_capture_tick_hmc <= hmc_tick_hmc;
        trigger_accepted_hmc <= 1'b1;
        trigger_accepted_count_hmc <= trigger_accepted_count_hmc + 1'b1;
        launch_pending_hmc <= 1'b1;
        trigger_event_external_hmc <= external_trigger_accept_hmc;
        trigger_wait_rearm_hmc <= 1'b1;
        trigger_seen_unprepared_hmc <= 1'b0;
        launch_count <= role_master ? MASTER_LAUNCH_DELAY_CYCLES : SLAVE_LAUNCH_DELAY_CYCLES;
        if (role_master) begin
          trigger_link_hmc <= 1'b1;
          trigger_high_count <= TRIGGER_HIGH_CYCLES;
          trigger_output_count_hmc <= trigger_output_count_hmc + 1'b1;
        end
      end

      // EMIT_TRIGGER is an explicit host request, so honour it on a slave too:
      // that is what lets a single board loop XS18 back into XS19 and trigger
      // itself.  The automatic forward above stays master-only, because that is
      // the master->slave path and a slave must not echo XS19 back out.
      if (emit_trigger_hmc_pulse && sync_trigger_allowed_hmc) begin
        trigger_link_hmc <= 1'b1;
        trigger_high_count <= TRIGGER_HIGH_CYCLES;
        trigger_output_count_hmc <= trigger_output_count_hmc + 1'b1;
      end

      if (launch_pending_hmc) begin
        if (launch_count == {LAUNCH_COUNT_WIDTH{1'b0}}) begin
          launch_pending_hmc <= 1'b0;
          trigger_event_toggle_hmc <= ~trigger_event_toggle_hmc;
          trigger_event_pulse_hmc <= 1'b1;
          trigger_launch_tick_hmc <= hmc_tick_hmc;
        end else begin
          launch_count <= launch_count - 1'b1;
        end
      end
    end
  end

  // Status is synchronized to PS pl_clk.  Its latency is irrelevant to the
  // physical event path and only controls firmware/driver observability.
  (* ASYNC_REG = "TRUE", SHREG_EXTRACT = "NO" *) reg [1:0] sync_done_pl_sync;
  (* ASYNC_REG = "TRUE", SHREG_EXTRACT = "NO" *) reg [1:0] sync_request_pl_sync;
  reg sync_done_pl_seen;
  reg sync_request_pl_seen;
  reg sync_done_pl_pulse;
  reg sync_seen_reg;
  reg sync_bypass_prev;
  reg [5:0] sync_event_epoch_reg;
  reg [5:0] sync_alignment_epoch_reg;
  reg sync_align_busy_reg;
  reg sync_align_failed_reg;
  reg sync_sequence_pending_reg;
  reg [31:0] trigger_input_count_reg;
  reg [31:0] trigger_accepted_count_reg;
  reg [31:0] trigger_output_count_reg;
  wire sync_request_pl_pulse = sync_request_pl_sync[1] != sync_request_pl_seen;
  wire sync_transaction_busy = sync_sequence_pending_reg || sync_align_busy_reg;

  always @(posedge pl_clk or negedge pl_rst_n) begin
    if (!pl_rst_n) begin
      sync_done_pl_sync <= 2'b00;
      sync_request_pl_sync <= 2'b00;
      sync_done_pl_seen <= 1'b0;
      sync_request_pl_seen <= 1'b0;
      sync_done_pl_pulse <= 1'b0;
      sync_link_ready_reg <= 1'b0;
      sync_seen_reg <= 1'b0;
      sync_bypass_prev <= 1'b0;
      sync_event_epoch_reg <= 6'd0;
      sync_alignment_epoch_reg <= 6'd0;
      sync_align_busy_reg <= 1'b0;
      sync_align_failed_reg <= 1'b0;
      sync_sequence_pending_reg <= 1'b0;
      trigger_input_count_reg <= 32'd0;
      trigger_accepted_count_reg <= 32'd0;
      trigger_output_count_reg <= 32'd0;
    end else begin
      sync_done_pl_sync <= {sync_done_pl_sync[0], sync_done_toggle_hmc};
      sync_request_pl_sync <= {sync_request_pl_sync[0], sync_request_toggle_ddr};
      sync_done_pl_pulse <= sync_done_pl_sync[1] != sync_done_pl_seen;
      if (sync_done_pl_sync[1] != sync_done_pl_seen)
        sync_done_pl_seen <= sync_done_pl_sync[1];
      if (sync_request_pl_pulse)
        sync_request_pl_seen <= sync_request_pl_sync[1];

      sync_bypass_prev <= sync_bypass;
      if (role_master && sync_request_pl_pulse) begin
        sync_sequence_pending_reg <= 1'b1;
        sync_align_failed_reg <= 1'b0;
        sync_link_ready_reg <= 1'b0;
      end
      if (sync_done_pl_pulse) begin
        sync_sequence_pending_reg <= 1'b0;
        sync_event_epoch_reg <= sync_event_epoch_reg + 1'b1;
        sync_align_busy_reg <= 1'b1;
        sync_align_failed_reg <= 1'b0;
        sync_link_ready_reg <= 1'b0;
        sync_seen_reg <= 1'b1;
      end else if (sync_align_busy_reg) begin
        if (firmware_align_failed && (firmware_ack_epoch == sync_event_epoch_reg)) begin
          sync_align_failed_reg <= 1'b1;
        end else if (firmware_ack_epoch == sync_event_epoch_reg) begin
          sync_alignment_epoch_reg <= firmware_ack_epoch;
          sync_align_busy_reg <= 1'b0;
          sync_align_failed_reg <= 1'b0;
          sync_link_ready_reg <= 1'b1;
        end
      end

      if (role_master && !sync_transaction_busy && !sync_align_failed_reg)
        sync_link_ready_reg <= 1'b1;
      else if (!role_master && sync_bypass)
        sync_link_ready_reg <= 1'b1;
      else if (!role_master && sync_bypass != sync_bypass_prev) begin
        sync_seen_reg <= 1'b0;
        sync_link_ready_reg <= sync_bypass;
      end

      trigger_input_count_reg <= trigger_input_count_hmc;
      trigger_accepted_count_reg <= trigger_accepted_count_hmc;
      trigger_output_count_reg <= trigger_output_count_hmc;
    end
  end

  assign hmc_sync = sync_hmc_internal;
  assign sync_link_out = sync_link_internal;
  assign trigger_link_out = trigger_link_hmc;
  assign role_trigger_raw = trigger_event_pulse_hmc;
  assign trigger_event_toggle = trigger_event_toggle_hmc;
  assign trigger_event_external = trigger_event_external_hmc;
  assign sync_done = sync_done_pl_pulse;
  assign sync_seen = sync_seen_reg;
  assign sync_link_ready = sync_link_ready_reg;
  assign sync_event_epoch = sync_event_epoch_reg;
  assign sync_align_busy = sync_transaction_busy;
  assign sync_align_failed = sync_align_failed_reg;
  assign sync_alignment_epoch = sync_alignment_epoch_reg;
  assign trigger_in_seen = trigger_in_seen_hmc;
  assign trigger_accepted = trigger_accepted_hmc;
  assign trigger_output_active = trigger_output_active_hmc;
  assign trigger_input_count = trigger_input_count_reg;
  assign trigger_accepted_count = trigger_accepted_count_reg;
  assign trigger_output_count = trigger_output_count_reg;
  assign hmc_event_tick = hmc_tick_hmc;
  assign sync_event_tick = sync_tick_hmc;
  assign trigger_capture_tick = trigger_capture_tick_hmc;
  assign trigger_launch_tick = trigger_launch_tick_hmc;
endmodule
