// Detect which 4ns phase slot an external trigger falls into within the 20ns
// dac_axis_clk beat, for software compensation of the 250MHz-grid quantization.
//
// The external trigger (XS19, TRIG_2) arrives on a 250 MHz = 4 ns grid from a
// source that shares the same 250 MHz rubidium reference but has an independent
// divider chain with arbitrary power-on phase.  Our dac_axis_clk is 50 MHz = 20
// ns, derived from the same reference via HMC7044 + RFDC internal PLL.  The
// trigger edge can land at 0, 4, 8, 12, or 16 ns within our 20 ns beat, giving
// five discrete delay slots that show up as ~16 ns jitter on the scope.
//
// This module oversamples the trigger input at 200 MHz (5 ns resolution) for one
// full dac_axis_clk cycle, counts how many clocks elapsed from the beat edge to
// the trigger edge, and reports which slot (0-4) the trigger occupied.  Software
// reads the slot and compensates by shifting the waveform record by 0/1/3/5/7
// fabric samples (0/2.5/7.5/12.5/17.5 ns), bringing the effective jitter from 16
// ns down to ~2 ns (the residual from 2.5 ns compensation grid vs 4 ns trigger
// grid being non-integer-divisible).
//
// The 200 MHz clock is generated by a fabric MMCM from dac_axis_clk.  Detection
// runs continuously; slot_id is valid any time slot_valid is high (one cycle
// after a trigger is sampled).  If no trigger arrives, slot_valid stays low and
// slot_id holds the last detected value.

module trigger_phase_detector (
    input  wire        clk_dac_50mhz,     // dac_axis_clk domain (20 ns period)
    input  wire        clk_sample_200mhz, // 4× oversampling clock (5 ns period)
    input  wire        rst_n,
    input  wire        trigger_in,        // async external trigger (XS19)
    output reg  [2:0]  slot_id,           // 0-4: trigger at 0/4/8/12/16ns in beat
    output reg         slot_valid         // pulsed high for one clk_dac_50mhz cycle
);

  // Synchronize the 50 MHz beat edge into the 200 MHz domain (3-FF)
  reg [2:0] beat_sync;
  always @(posedge clk_sample_200mhz or negedge rst_n) begin
    if (!rst_n) beat_sync <= 3'b0;
    else        beat_sync <= {beat_sync[1:0], clk_dac_50mhz};
  end
  wire beat_rise = beat_sync[2:1] == 2'b01;

  // Synchronize the trigger into 200 MHz (3-FF)
  reg [2:0] trig_sync;
  always @(posedge clk_sample_200mhz or negedge rst_n) begin
    if (!rst_n) trig_sync <= 3'b0;
    else        trig_sync <= {trig_sync[1:0], trigger_in};
  end
  wire trig_rise = trig_sync[2:1] == 2'b01;

  // Count 200 MHz clocks from beat edge; saturate at 4 (covers 0-20ns)
  reg [2:0] phase_count;
  reg       count_active;
  always @(posedge clk_sample_200mhz or negedge rst_n) begin
    if (!rst_n) begin
      phase_count  <= 3'd0;
      count_active <= 1'b0;
    end else begin
      if (beat_rise) begin
        phase_count  <= 3'd0;
        count_active <= 1'b1;
      end else if (count_active && phase_count < 3'd4) begin
        phase_count <= phase_count + 1'b1;
      end
      // Stop counting at 4 (one past the last valid slot)
    end
  end

  // Capture slot when trigger rises
  reg [2:0] captured_slot;
  reg       capture_flag;
  always @(posedge clk_sample_200mhz or negedge rst_n) begin
    if (!rst_n) begin
      captured_slot <= 3'd0;
      capture_flag  <= 1'b0;
    end else begin
      if (trig_rise && count_active) begin
        // Clamp to 4 if trigger arrived late (>16ns into beat)
        captured_slot <= (phase_count > 3'd4) ? 3'd4 : phase_count;
        capture_flag  <= 1'b1;
      end else if (beat_rise) begin
        capture_flag <= 1'b0;  // clear flag at next beat
      end
    end
  end

  // CDC back to 50 MHz domain: the captured slot is stable for nearly a full
  // 20ns cycle, so a plain 2-FF synchronizer is safe.  Pulse slot_valid for one
  // cycle when capture_flag rises in the 50 MHz domain.
  reg [1:0] flag_sync;
  reg       flag_prev;
  always @(posedge clk_dac_50mhz or negedge rst_n) begin
    if (!rst_n) begin
      flag_sync <= 2'b0;
      flag_prev <= 1'b0;
      slot_id   <= 3'd0;
      slot_valid<= 1'b0;
    end else begin
      flag_sync <= {flag_sync[0], capture_flag};
      flag_prev <= flag_sync[1];
      slot_valid<= flag_sync[1] && !flag_prev;  // rising edge -> one-cycle pulse
      if (slot_valid) begin
        slot_id <= captured_slot;  // latch on the pulse
      end
    end
  end

endmodule
