package rfdc

import java.nio.charset.StandardCharsets
import java.nio.file.{Files, Paths}

object elaborate extends App {
  private val outputDir = Paths.get("generated")
  Files.createDirectories(outputDir)

  private val outputPath = outputDir.resolve("rfdc_custom_xczu47dr_config.tcl")
  private val config = RfdcCustomXczu47drConfig.renderTcl
  Files.write(outputPath, config.getBytes(StandardCharsets.UTF_8))
  println(s"RFDC Vivado configuration generated: ${outputPath.toString}")
}

object RfdcCustomXczu47drConfig {
  private val axisFreqHz = 312500000
  private val refclkFreqHz = 125000000
  private val outclkFreqHz = 312500000

  private val configEntries = Seq(
    "CONFIG.ADC_Slice00_Enable {false}",
    "CONFIG.ADC_Slice20_Enable {false}",
    "CONFIG.ADC_Slice22_Enable {false}",
    "CONFIG.ADC_Slice30_Enable {false}",
    "CONFIG.DAC2_Clock_Dist {2}",
    "CONFIG.DAC2_Clock_Source {6}",
    "CONFIG.DAC2_Outclk_Freq {312.500}",
    "CONFIG.DAC2_PLL_Enable {true}",
    "CONFIG.DAC2_Refclk_Freq {125.000}",
    "CONFIG.DAC2_Sampling_Rate {5.0}",
    "CONFIG.DAC3_Clock_Source {6}",
    "CONFIG.DAC3_Fabric_Freq {312.500}",
    "CONFIG.DAC3_Outclk_Freq {312.500}",
    "CONFIG.DAC3_PLL_Enable {false}",
    "CONFIG.DAC3_Sampling_Rate {5.0}",
    "CONFIG.DAC_Coarse_Mixer_Freq20 {3}",
    "CONFIG.DAC_Coarse_Mixer_Freq22 {3}",
    "CONFIG.DAC_Coarse_Mixer_Freq30 {3}",
    "CONFIG.DAC_Coarse_Mixer_Freq32 {3}",
    "CONFIG.DAC_Data_Width20 {4}",
    "CONFIG.DAC_Data_Width22 {4}",
    "CONFIG.DAC_Data_Width30 {4}",
    "CONFIG.DAC_Data_Width32 {4}",
    "CONFIG.DAC_Interpolation_Mode20 {4}",
    "CONFIG.DAC_Interpolation_Mode22 {4}",
    "CONFIG.DAC_Interpolation_Mode30 {4}",
    "CONFIG.DAC_Interpolation_Mode32 {4}",
    "CONFIG.DAC_Mixer_Mode20 {2}",
    "CONFIG.DAC_Mixer_Mode22 {2}",
    "CONFIG.DAC_Mixer_Mode30 {2}",
    "CONFIG.DAC_Mixer_Mode32 {2}",
    "CONFIG.DAC_Mixer_Type20 {1}",
    "CONFIG.DAC_Mixer_Type22 {1}",
    "CONFIG.DAC_Mixer_Type30 {1}",
    "CONFIG.DAC_Mixer_Type32 {1}",
    "CONFIG.DAC_Nyquist20 {1}",
    "CONFIG.DAC_Nyquist22 {1}",
    "CONFIG.DAC_Nyquist30 {1}",
    "CONFIG.DAC_Nyquist32 {1}",
    "CONFIG.DAC_Slice00_Enable {false}",
    "CONFIG.DAC_Slice20_Enable {true}",
    "CONFIG.DAC_Slice22_Enable {true}",
    "CONFIG.DAC_Slice30_Enable {true}",
    "CONFIG.DAC_Slice32_Enable {true}",
    "CONFIG.DAC_VOP_Mode {1}",
    "CONFIG.RF_Analyzer {1}"
  )

  def renderTcl: String = {
    val body = configEntries.zipWithIndex.map { case (entry, index) =>
      val suffix = if (index == configEntries.size - 1) "" else " \\"
      s"      $entry$suffix"
    }.mkString("\n")

    s"""# Generated by hardware/chisel/rfdc/src/elaborate.scala. Do not edit by hand.
# Custom XCZU47DR RFDC configuration for 125 MHz refclk, 5.0 GS/s DACs,
# 1.25 GS/s PL stream, and Zone2 image playback.

namespace eval ::rfdc_custom_xczu47dr {
  proc axis_freq_hz {} { return $axisFreqHz }
  proc refclk_freq_hz {} { return $refclkFreqHz }
  proc outclk_freq_hz {} { return $outclkFreqHz }
  proc associated_busif {} { return {S_AXIS_20:S_AXIS_22:S_AXIS_30:S_AXIS_32} }

  proc config {} {
    return [list \\
$body]
  }
}
"""
  }
}
