package rfdc

import java.nio.charset.StandardCharsets
import java.nio.file.{Files, Paths}

object elaborate extends App {
  private val outputDir = Paths.get("generated")
  Files.createDirectories(outputDir)

  private val configPath = outputDir.resolve("rfdc_custom_xczu47dr_config.tcl")
  private val config = RfdcCustomXczu47drConfig.renderTcl
  Files.write(configPath, config.getBytes(StandardCharsets.UTF_8))
  println(s"RFDC Vivado configuration generated: ${configPath.toString}")

  private val wrapperPath = outputDir.resolve("RfdcCustomXczu47dr.v")
  private val wrapper = RfdcCustomXczu47drConfig.renderWrapperVerilog
  Files.write(wrapperPath, wrapper.getBytes(StandardCharsets.UTF_8))
  println(s"RFDC Verilog blackbox wrapper generated: ${wrapperPath.toString}")
}

object RfdcCustomXczu47drConfig {
  // 8-channel DAC playback: 4 DAC tiles (228..231) x 2 DAC blocks each.
  // C2R (IQ -> Real) with fine NCO digital up-conversion to 4-5 GHz.
  // Fs = 6.0 GSPS, 8x interpolation => fabric/AXIS clock 93.75 MHz.
  // The high interpolation keeps the per-tile 256-bit AXIS consumption rate
  // (256b x 93.75 MHz = 24 Gbit/s) below the sustainable 128-bit DDR read
  // bandwidth, so a single active tile can stream a continuous CW tone without
  // FIFO underflow. The fine NCO sits after interpolation, so its 4-5 GHz tune
  // range is unaffected, and the narrow single-tone images are cleaner.
  // DAC2 (tile 230) owns the PLL from a 125 MHz refclk and distributes the
  // sampling clock to all four tiles (Clock_Source=6 on every tile).
  private val axisFreqHz = 93750000
  private val refclkFreqHz = 125000000
  private val outclkFreqHz = 93750000

  // Interpolation factor applied on every used DAC slice.
  private val interpolationMode = "8"

  // Default fine-NCO baseband frequency in GHz. The Real output lands in
  // Nyquist Zone 2 of the 6.0 GSPS DAC, so the 1.5 GHz NCO image appears at
  // 6.0 - 1.5 = 4.5 GHz. Firmware can retune the NCO at runtime.
  private val ncoFreqGHz = "1.5"

  // Used DAC slices per tile: block 0 and block 2 (the two physical DACs).
  private val usedSlices = Seq("0", "2")
  private val tiles = Seq("0", "1", "2", "3")

  private val configEntries: Seq[String] = {
    val adcDisable =
      tiles.map(t => s"CONFIG.ADC${t}_Enable {0}") ++
        (for (t <- tiles; s <- Seq("0", "1", "2", "3"))
          yield s"CONFIG.ADC_Slice${t}${s}_Enable {false}")

    // Per-tile clocking. DAC2 is the distribution source.
    val tileClock = tiles.flatMap { t =>
      val base = Seq(
        s"CONFIG.DAC${t}_Enable {1}",
        s"CONFIG.DAC${t}_Sampling_Rate {6.0}",
        s"CONFIG.DAC${t}_Clock_Source {6}"
      )
      if (t == "2")
        base ++ Seq(
          "CONFIG.DAC2_PLL_Enable {true}",
          "CONFIG.DAC2_Refclk_Freq {125.000}",
          "CONFIG.DAC2_Clock_Dist {2}"
        )
      else
        base ++ Seq(
          s"CONFIG.DAC${t}_PLL_Enable {false}",
          s"CONFIG.DAC${t}_Clock_Dist {0}"
        )
    }

    // Per used-slice datapath: enable, 2x interpolation, C2R fine-NCO mixer,
    // complex (IQ) input data type, Zone2, and the default NCO frequency.
    val sliceCfg = for (t <- tiles; s <- usedSlices) yield Seq(
      s"CONFIG.DAC_Slice${t}${s}_Enable {true}",
      s"CONFIG.DAC_Interpolation_Mode${t}${s} {$interpolationMode}",
      s"CONFIG.DAC_Mixer_Mode${t}${s} {1}",
      s"CONFIG.DAC_Mixer_Type${t}${s} {2}",
      s"CONFIG.DAC_Data_Type${t}${s} {1}",
      s"CONFIG.DAC_NCO_Freq${t}${s} {$ncoFreqGHz}",
      s"CONFIG.DAC_Nyquist${t}${s} {1}"
    )

    val sliceDisable = for (t <- tiles; s <- Seq("1", "3"))
      yield s"CONFIG.DAC_Slice${t}${s}_Enable {false}"

    adcDisable ++ tileClock ++ sliceCfg.flatten ++ sliceDisable ++ Seq(
      "CONFIG.DAC_VOP_Mode {1}",
      "CONFIG.RF_Analyzer {1}"
    )
  }

  def renderTcl: String = {
    val body = configEntries.zipWithIndex.map { case (entry, index) =>
      val suffix = if (index == configEntries.size - 1) "" else " \\"
      s"      $entry$suffix"
    }.mkString("\n")

    s"""# Generated by hardware/chisel/rfdc/src/elaborate.scala. Do not edit by hand.
# Custom XCZU47DR RFDC configuration for 125 MHz refclk, 6.0 GS/s DACs,
# 8-channel C2R (IQ->Real) fine-NCO digital up-conversion, 93.75 MHz PL stream.

namespace eval ::rfdc_custom_xczu47dr {
  proc axis_freq_hz {} { return $axisFreqHz }
  proc refclk_freq_hz {} { return $refclkFreqHz }
  proc outclk_freq_hz {} { return $outclkFreqHz }
  proc associated_busif {} { return {s00_axis:s10_axis:s20_axis:s30_axis} }

  proc config {} {
    return [list \\
$body]
  }
}
"""
  }

  def renderWrapperVerilog: String = {
    """// Generated by hardware/chisel/rfdc/src/elaborate.scala. Do not edit by hand.
// Top-level blackbox wrapper for the Vivado-managed RFDC IP.

module RfdcCustomXczu47dr (
    input          s_axi_aclk,
    input          s_axi_aresetn,
    input  [17:0]  s_axi_awaddr,
    input          s_axi_awvalid,
    output         s_axi_awready,
    input  [31:0]  s_axi_wdata,
    input  [3:0]   s_axi_wstrb,
    input          s_axi_wvalid,
    output         s_axi_wready,
    output [1:0]   s_axi_bresp,
    output         s_axi_bvalid,
    input          s_axi_bready,
    input  [17:0]  s_axi_araddr,
    input          s_axi_arvalid,
    output         s_axi_arready,
    output [31:0]  s_axi_rdata,
    output [1:0]   s_axi_rresp,
    output         s_axi_rvalid,
    input          s_axi_rready,
    input          sysref_in_p,
    input          sysref_in_n,
    input          dac2_clk_p,
    input          dac2_clk_n,
    output         clk_dac0,
    output         clk_dac1,
    output         clk_dac2,
    output         clk_dac3,
    input          s0_axis_aclk,
    input          s0_axis_aresetn,
    input          s1_axis_aclk,
    input          s1_axis_aresetn,
    input          s2_axis_aclk,
    input          s2_axis_aresetn,
    input          s3_axis_aclk,
    input          s3_axis_aresetn,
    output         vout00_p,
    output         vout00_n,
    output         vout02_p,
    output         vout02_n,
    output         vout10_p,
    output         vout10_n,
    output         vout12_p,
    output         vout12_n,
    output         vout20_p,
    output         vout20_n,
    output         vout22_p,
    output         vout22_n,
    output         vout30_p,
    output         vout30_n,
    output         vout32_p,
    output         vout32_n,
    input  [255:0] s00_axis_tdata,
    input          s00_axis_tvalid,
    output         s00_axis_tready,
    input  [255:0] s10_axis_tdata,
    input          s10_axis_tvalid,
    output         s10_axis_tready,
    input  [255:0] s20_axis_tdata,
    input          s20_axis_tvalid,
    output         s20_axis_tready,
    input  [255:0] s30_axis_tdata,
    input          s30_axis_tvalid,
    output         s30_axis_tready,
    output         irq
);

  rfdc_custom_xczu47dr_ip rfdc_custom_xczu47dr_ip_i (
      .s_axi_aclk(s_axi_aclk),
      .s_axi_aresetn(s_axi_aresetn),
      .s_axi_awaddr(s_axi_awaddr),
      .s_axi_awvalid(s_axi_awvalid),
      .s_axi_awready(s_axi_awready),
      .s_axi_wdata(s_axi_wdata),
      .s_axi_wstrb(s_axi_wstrb),
      .s_axi_wvalid(s_axi_wvalid),
      .s_axi_wready(s_axi_wready),
      .s_axi_bresp(s_axi_bresp),
      .s_axi_bvalid(s_axi_bvalid),
      .s_axi_bready(s_axi_bready),
      .s_axi_araddr(s_axi_araddr),
      .s_axi_arvalid(s_axi_arvalid),
      .s_axi_arready(s_axi_arready),
      .s_axi_rdata(s_axi_rdata),
      .s_axi_rresp(s_axi_rresp),
      .s_axi_rvalid(s_axi_rvalid),
      .s_axi_rready(s_axi_rready),
      .sysref_in_p(sysref_in_p),
      .sysref_in_n(sysref_in_n),
      .dac2_clk_p(dac2_clk_p),
      .dac2_clk_n(dac2_clk_n),
      .clk_dac0(clk_dac0),
      .clk_dac1(clk_dac1),
      .clk_dac2(clk_dac2),
      .clk_dac3(clk_dac3),
      .s0_axis_aclk(s0_axis_aclk),
      .s0_axis_aresetn(s0_axis_aresetn),
      .s1_axis_aclk(s1_axis_aclk),
      .s1_axis_aresetn(s1_axis_aresetn),
      .s2_axis_aclk(s2_axis_aclk),
      .s2_axis_aresetn(s2_axis_aresetn),
      .s3_axis_aclk(s3_axis_aclk),
      .s3_axis_aresetn(s3_axis_aresetn),
      .vout00_p(vout00_p),
      .vout00_n(vout00_n),
      .vout02_p(vout02_p),
      .vout02_n(vout02_n),
      .vout10_p(vout10_p),
      .vout10_n(vout10_n),
      .vout12_p(vout12_p),
      .vout12_n(vout12_n),
      .vout20_p(vout20_p),
      .vout20_n(vout20_n),
      .vout22_p(vout22_p),
      .vout22_n(vout22_n),
      .vout30_p(vout30_p),
      .vout30_n(vout30_n),
      .vout32_p(vout32_p),
      .vout32_n(vout32_n),
      .s00_axis_tdata(s00_axis_tdata),
      .s00_axis_tvalid(s00_axis_tvalid),
      .s00_axis_tready(s00_axis_tready),
      .s10_axis_tdata(s10_axis_tdata),
      .s10_axis_tvalid(s10_axis_tvalid),
      .s10_axis_tready(s10_axis_tready),
      .s20_axis_tdata(s20_axis_tdata),
      .s20_axis_tvalid(s20_axis_tvalid),
      .s20_axis_tready(s20_axis_tready),
      .s30_axis_tdata(s30_axis_tdata),
      .s30_axis_tvalid(s30_axis_tvalid),
      .s30_axis_tready(s30_axis_tready),
      .irq(irq)
  );

endmodule
"""
  }
}
