package rfdc

import java.nio.charset.StandardCharsets
import java.nio.file.{Files, Paths}

object elaborate extends App {
  private val outputDir = Paths.get("generated")
  Files.createDirectories(outputDir)

  private val configPath = outputDir.resolve("rfdc_custom_xczu47dr_config.tcl")
  private val config = RfdcCustomXczu47drConfig.renderTcl
  Files.write(configPath, config.getBytes(StandardCharsets.UTF_8))
  println(s"RFDC Vivado configuration generated: ${configPath.toString}")

  private val wrapperPath = outputDir.resolve("RfdcCustomXczu47dr.v")
  private val wrapper = RfdcCustomXczu47drConfig.renderWrapperVerilog
  Files.write(wrapperPath, wrapper.getBytes(StandardCharsets.UTF_8))
  println(s"RFDC Verilog blackbox wrapper generated: ${wrapperPath.toString}")
}

object RfdcCustomXczu47drConfig {
  private val axisFreqHz = 312500000
  private val refclkFreqHz = 125000000
  private val outclkFreqHz = 312500000

  private val configEntries = Seq(
    "CONFIG.ADC_Slice00_Enable {false}",
    "CONFIG.ADC_Slice20_Enable {false}",
    "CONFIG.ADC_Slice22_Enable {false}",
    "CONFIG.ADC_Slice30_Enable {false}",
    "CONFIG.DAC2_Clock_Dist {2}",
    "CONFIG.DAC2_Clock_Source {6}",
    "CONFIG.DAC2_Outclk_Freq {312.500}",
    "CONFIG.DAC2_PLL_Enable {true}",
    "CONFIG.DAC2_Refclk_Freq {125.000}",
    "CONFIG.DAC2_Sampling_Rate {5.0}",
    "CONFIG.DAC3_Clock_Source {6}",
    "CONFIG.DAC3_Fabric_Freq {312.500}",
    "CONFIG.DAC3_Outclk_Freq {312.500}",
    "CONFIG.DAC3_PLL_Enable {false}",
    "CONFIG.DAC3_Sampling_Rate {5.0}",
    "CONFIG.DAC_Coarse_Mixer_Freq20 {3}",
    "CONFIG.DAC_Coarse_Mixer_Freq22 {3}",
    "CONFIG.DAC_Coarse_Mixer_Freq30 {3}",
    "CONFIG.DAC_Coarse_Mixer_Freq32 {3}",
    "CONFIG.DAC_Data_Width20 {4}",
    "CONFIG.DAC_Data_Width22 {4}",
    "CONFIG.DAC_Data_Width30 {4}",
    "CONFIG.DAC_Data_Width32 {4}",
    "CONFIG.DAC_Interpolation_Mode20 {4}",
    "CONFIG.DAC_Interpolation_Mode22 {4}",
    "CONFIG.DAC_Interpolation_Mode30 {4}",
    "CONFIG.DAC_Interpolation_Mode32 {4}",
    "CONFIG.DAC_Mixer_Mode20 {2}",
    "CONFIG.DAC_Mixer_Mode22 {2}",
    "CONFIG.DAC_Mixer_Mode30 {2}",
    "CONFIG.DAC_Mixer_Mode32 {2}",
    "CONFIG.DAC_Mixer_Type20 {1}",
    "CONFIG.DAC_Mixer_Type22 {1}",
    "CONFIG.DAC_Mixer_Type30 {1}",
    "CONFIG.DAC_Mixer_Type32 {1}",
    "CONFIG.DAC_Nyquist20 {1}",
    "CONFIG.DAC_Nyquist22 {1}",
    "CONFIG.DAC_Nyquist30 {1}",
    "CONFIG.DAC_Nyquist32 {1}",
    "CONFIG.DAC_Slice00_Enable {false}",
    "CONFIG.DAC_Slice20_Enable {true}",
    "CONFIG.DAC_Slice22_Enable {true}",
    "CONFIG.DAC_Slice30_Enable {true}",
    "CONFIG.DAC_Slice32_Enable {true}",
    "CONFIG.DAC_VOP_Mode {1}",
    "CONFIG.RF_Analyzer {1}"
  )

  def renderTcl: String = {
    val body = configEntries.zipWithIndex.map { case (entry, index) =>
      val suffix = if (index == configEntries.size - 1) "" else " \\"
      s"      $entry$suffix"
    }.mkString("\n")

    s"""# Generated by hardware/chisel/rfdc/src/elaborate.scala. Do not edit by hand.
# Custom XCZU47DR RFDC configuration for 125 MHz refclk, 5.0 GS/s DACs,
# 1.25 GS/s PL stream, and Zone2 image playback.

namespace eval ::rfdc_custom_xczu47dr {
  proc axis_freq_hz {} { return $axisFreqHz }
  proc refclk_freq_hz {} { return $refclkFreqHz }
  proc outclk_freq_hz {} { return $outclkFreqHz }
  proc associated_busif {} { return {S_AXIS_20:S_AXIS_22:S_AXIS_30:S_AXIS_32} }

  proc config {} {
    return [list \\
$body]
  }
}
"""
  }

  def renderWrapperVerilog: String = {
    """// Generated by hardware/chisel/rfdc/src/elaborate.scala. Do not edit by hand.
// Top-level blackbox wrapper for the Vivado-managed RFDC IP.

module RfdcCustomXczu47dr (
    input         s_axi_aclk,
    input         s_axi_aresetn,
    input  [17:0] s_axi_awaddr,
    input         s_axi_awvalid,
    output        s_axi_awready,
    input  [31:0] s_axi_wdata,
    input  [3:0]  s_axi_wstrb,
    input         s_axi_wvalid,
    output        s_axi_wready,
    output [1:0]  s_axi_bresp,
    output        s_axi_bvalid,
    input         s_axi_bready,
    input  [17:0] s_axi_araddr,
    input         s_axi_arvalid,
    output        s_axi_arready,
    output [31:0] s_axi_rdata,
    output [1:0]  s_axi_rresp,
    output        s_axi_rvalid,
    input         s_axi_rready,
    input         sysref_in_p,
    input         sysref_in_n,
    input         dac2_clk_p,
    input         dac2_clk_n,
    output        clk_dac2,
    input         s2_axis_aclk,
    input         s2_axis_aresetn,
    output        clk_dac3,
    input         s3_axis_aclk,
    input         s3_axis_aresetn,
    output        vout20_p,
    output        vout20_n,
    output        vout22_p,
    output        vout22_n,
    output        vout30_p,
    output        vout30_n,
    output        vout32_p,
    output        vout32_n,
    input  [63:0] s20_axis_tdata,
    input         s20_axis_tvalid,
    output        s20_axis_tready,
    input  [63:0] s22_axis_tdata,
    input         s22_axis_tvalid,
    output        s22_axis_tready,
    input  [63:0] s30_axis_tdata,
    input         s30_axis_tvalid,
    output        s30_axis_tready,
    input  [63:0] s32_axis_tdata,
    input         s32_axis_tvalid,
    output        s32_axis_tready,
    output        irq
);

  rfdc_custom_xczu47dr_ip rfdc_custom_xczu47dr_ip_i (
      .s_axi_aclk(s_axi_aclk),
      .s_axi_aresetn(s_axi_aresetn),
      .s_axi_awaddr(s_axi_awaddr),
      .s_axi_awvalid(s_axi_awvalid),
      .s_axi_awready(s_axi_awready),
      .s_axi_wdata(s_axi_wdata),
      .s_axi_wstrb(s_axi_wstrb),
      .s_axi_wvalid(s_axi_wvalid),
      .s_axi_wready(s_axi_wready),
      .s_axi_bresp(s_axi_bresp),
      .s_axi_bvalid(s_axi_bvalid),
      .s_axi_bready(s_axi_bready),
      .s_axi_araddr(s_axi_araddr),
      .s_axi_arvalid(s_axi_arvalid),
      .s_axi_arready(s_axi_arready),
      .s_axi_rdata(s_axi_rdata),
      .s_axi_rresp(s_axi_rresp),
      .s_axi_rvalid(s_axi_rvalid),
      .s_axi_rready(s_axi_rready),
      .sysref_in_p(sysref_in_p),
      .sysref_in_n(sysref_in_n),
      .dac2_clk_p(dac2_clk_p),
      .dac2_clk_n(dac2_clk_n),
      .clk_dac2(clk_dac2),
      .s2_axis_aclk(s2_axis_aclk),
      .s2_axis_aresetn(s2_axis_aresetn),
      .clk_dac3(clk_dac3),
      .s3_axis_aclk(s3_axis_aclk),
      .s3_axis_aresetn(s3_axis_aresetn),
      .vout20_p(vout20_p),
      .vout20_n(vout20_n),
      .vout22_p(vout22_p),
      .vout22_n(vout22_n),
      .vout30_p(vout30_p),
      .vout30_n(vout30_n),
      .vout32_p(vout32_p),
      .vout32_n(vout32_n),
      .s20_axis_tdata(s20_axis_tdata),
      .s20_axis_tvalid(s20_axis_tvalid),
      .s20_axis_tready(s20_axis_tready),
      .s22_axis_tdata(s22_axis_tdata),
      .s22_axis_tvalid(s22_axis_tvalid),
      .s22_axis_tready(s22_axis_tready),
      .s30_axis_tdata(s30_axis_tdata),
      .s30_axis_tvalid(s30_axis_tvalid),
      .s30_axis_tready(s30_axis_tready),
      .s32_axis_tdata(s32_axis_tdata),
      .s32_axis_tvalid(s32_axis_tvalid),
      .s32_axis_tready(s32_axis_tready),
      .irq(irq)
  );

endmodule
"""
  }
}
